module.exports = {
  name: 'All Products Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesAllProductsPageCheck',
      path: '/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsUnitedStates',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyAllProductsPageCheck',
      path: '/de/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceAllProductsPageCheck',
      path: '/fr/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyAllProductsPageCheck',
      path: '/it/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomAllProductsPageCheck',
      path: '/uk/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaAllProductsPageCheck',
      path: '/mena_ar/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanAllProductsPageCheck',
      path: '/jp/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaAllProductsPageCheck',
      path: '/in/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainAllProductsPageCheck',
      path: '/es/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsSpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishAllProductsPageCheck',
      path: '/ca/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsCanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaAllProductsPageCheck',
      path: '/kr/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchAllProductsPageCheck',
      path: '/ca_fr/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsCanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandAllProductsPageCheck',
      path: '/pl/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsPoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoAllProductsPageCheck',
      path: '/mx/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaAllProductsPageCheck',
      path: '/au/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaAllProductsPageCheck',
      path: '/id_id/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishAllProductsPageCheck',
      path: '/id_en/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyAllProductsPageCheck',
      path: '/tr/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsTurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishAllProductsPageCheck',
      path: '/th_en/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandAllProductsPageCheck',
      path: '/th_th/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeAllProductsPageCheck',
      path: '/sg/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsSingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineAllProductsPageCheck',
      path: '/ph_fil/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsPhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippineEnglishAllProductsPageCheck',
      path: '/ph_fil/products/catalog.html#category=creativity-design?georouting=off',
      tags: '@allProductspagesanity @allproductsPhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
