module.exports = {
  name: 'Category Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesCategoryPageCheck',
      path: '/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryUnitedStatesPage',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyCategoryPageCheck',
      path: '/de/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceCategoryPageCheck',
      path: '/fr/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyCategoryPageCheck',
      path: '/it/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomCategoryPageCheck',
      path: '/uk/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaCategoryPageCheck',
      path: '/mena_ar/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanCategoryPageCheck',
      path: '/jp/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaCategoryPageCheck',
      path: '/in/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainCategoryPageCheck',
      path: '/es/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categorySpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishCategoryPageCheck',
      path: '/ca/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryCanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaCategoryPageCheck',
      path: '/kr/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchCategoryPageCheck',
      path: '/ca_fr/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryCanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandCategoryPageCheck',
      path: '/pl/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryPoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoCategoryPageCheck',
      path: '/mx/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaCategoryPageCheck',
      path: '/au/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaCategoryPageCheck',
      path: '/id_id/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishCategoryPageCheck',
      path: '/id_en/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyCategoryPageCheck',
      path: '/tr/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryTurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishCategoryPageCheck',
      path: '/th_en/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandCategoryPageCheck',
      path: '/th_th/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeCategoryPageCheck',
      path: '/sg/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categorySingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineCategoryPageCheck',
      path: '/ph_fil/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryPhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippineEnglishCategoryPageCheck',
      path: '/ph_en/creativecloud/plans.html?georouting=off',
      tags: '@categorypagesanity @categoryPhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
