module.exports = {
  name: 'Creative Cloud Enterprise Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesCCEPageCheck',
      path: '/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @cceUnitedStatesPage',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyCCEPageCheck',
      path: '/de/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @cceGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceCCEPageCheck',
      path: '/fr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyCCEPageCheck',
      path: '/it/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomCCEPageCheck',
      path: '/uk/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaCCEPageCheck',
      path: '/mena_ar/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanCCEPageCheck',
      path: '/jp/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaCCEPageCheck',
      path: '/in/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainCCEPageCheck',
      path: '/es/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCESpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishCCEPageCheck',
      path: '/ca/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCECanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaCCEPageCheck',
      path: '/kr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchCCEPageCheck',
      path: '/ca_fr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCECanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandCCEPageCheck',
      path: '/pl/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEPoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoCCEPageCheck',
      path: '/mx/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaCCEPageCheck',
      path: '/au/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaCCEPageCheck',
      path: '/id_id/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishCCEPageCheck',
      path: '/id_en/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyCCEPageCheck',
      path: '/tr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCETurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishCCEPageCheck',
      path: '/th_en/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandCCEPageCheck',
      path: '/th_th/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeCCEPageCheck',
      path: '/sg/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCESingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineCCEPageCheck',
      path: '/ph_fil/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEPhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippineEnglishCCEPageCheck',
      path: '/ph_en/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccepagesanity @CCEPhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
