module.exports = {
  name: 'Creative Cloud Teams Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesCCTPageCheck',
      path: '/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctUnitedStatesPage',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyCCTPageCheck',
      path: '/de/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctGermanyPage',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceCCTPageCheck',
      path: '/fr/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctFrancePage',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyCCTPageCheck',
      path: '/it/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctItalyPage',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomCCTPageCheck',
      path: '/uk/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctUnitedKingdomPage',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaCCTPageCheck',
      path: '/mena_ar/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctMiddleEastAndNorthAfricaPage',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanCCTPageCheck',
      path: '/jp/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctJapanPage',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaCCTPageCheck',
      path: '/in/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctIndiaPage',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainCCTPageCheck',
      path: '/es/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctSpainPage',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishCCTPageCheck',
      path: '/ca/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctCanadaEnglishPage',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaCCTPageCheck',
      path: '/kr/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctKoreaPage',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchCCTPageCheck',
      path: '/ca_fr/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctCanadaFrenchPage',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandCCTPageCheck',
      path: '/pl/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctPolandPage',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoCCTPageCheck',
      path: '/mx/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctMexicoPage',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaCCTPageCheck',
      path: '/au/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctAustraliaPage',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaCCTPageCheck',
      path: '/id_id/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctIndonesiaPage',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishCCTPageCheck',
      path: '/id_en/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctIndonesiaEnglishPage',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyCCTPageCheck',
      path: '/tr/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctTurkeyPage',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishCCTPageCheck',
      path: '/th_en/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctThailandEnglishPage',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandCCTPageCheck',
      path: '/th_th/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctThailandPage',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeCCTPageCheck',
      path: '/sg/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctSingaporePage',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineCCTPageCheck',
      path: '/ph_fil/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctPhilippinesPage',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippinesEnglishCCTPageCheck',
      path: '/ph_en/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@cctpagesanity @cctPhilippinesEnglishPage',
      country: 'Philippines English',
    },
  ],
};
