module.exports = {
    name: 'Creative Cloud UNAV Page',
    features: [
        {
            tcid: '0',
            name: '@UnitedStatesCCUnavPageCheck',
            path: '/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavUnitedStates',
            country: 'United States',
        },
        {
            tcid: '1',
            name: '@GermanyCCUnavPageCheck',
            path: '/de/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavGermany',
            country: 'Germany',
        },
        {
            tcid: '2',
            name: '@FranceCCUnavPageCheck',
            path: '/fr/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavFrance',
            country: 'France',
        },
        {
            tcid: '3',
            name: '@ItalyCCUnavPageCheck',
            path: '/it/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavItaly',
            country: 'Italy',
        },
        {
            tcid: '4',
            name: '@UnitedKingdomCCUnavPageCheck',
            path: '/uk/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavUnitedKingdom',
            country: 'United Kingdom',
        },
        {
            tcid: '5',
            name: '@MiddleEastAndNorthAfricaCCUnavPageCheck',
            path: '/mena_ar/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavMiddleEastAndNorthAfrica',
            country: 'Middle East And North Africa',
        },
        {
            tcid: '6',
            name: '@JapanCCUnavPageCheck',
            path: '/jp/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavJapan',
            country: 'Japan',
        },
        {
            tcid: '7',
            name: '@IndiaCCUnavPageCheck',
            path: '/in/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavIndia',
            country: 'India',
        },
        {
            tcid: '8',
            name: '@SpainCCUnavPageCheck',
            path: '/es/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavSpain',
            country: 'Spain',
        },
        {
            tcid: '9',
            name: '@CanadaEnglishCCUnavPageCheck',
            path: '/ca/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavCanadaEnglish',
            country: 'Canada English',
        },
        {
            tcid: '10',
            name: '@KoreaCCUnavPageCheck',
            path: '/kr/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavKorea',
            country: 'Korea',
        },
        {
            tcid: '11',
            name: '@CanadaFrenchCCUnavPageCheck',
            path: '/ca_fr/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavCanadaFrench',
            country: 'Canada French',
        },
        {
            tcid: '12',
            name: '@PolandCCUnavPageCheck',
            path: '/pl/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavPoland',
            country: 'Poland',
        },
        {
            tcid: '13',
            name: '@MexicoCCUnavPageCheck',
            path: '/mx/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavMexico',
            country: 'Mexico',
        },
        {
            tcid: '14',
            name: '@AustraliaCCUnavPageCheck',
            path: '/au/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavAustralia',
            country: 'Australia',
        },
        {
            tcid: '15',
            name: '@IndonesiaCCUnavPageCheck',
            path: '/id_id/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavIndonesia',
            country: 'Indonesia',
        },
        {
            tcid: '16',
            name: '@IndonesiaEnglishCCUnavPageCheck',
            path: '/id_en/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavIndonesiaEnglish',
            country: 'Indonesia English',
        },
        {
            tcid: '17',
            name: '@TurkeyCCUnavPageCheck',
            path: '/tr/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavTurkey',
            country: 'Turkey',
        },
        {
            tcid: '18',
            name: '@ThailandEnglishCCUnavPageCheck',
            path: '/th_en/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavThailandEnglish',
            country: 'Thailand English',
        },
        {
            tcid: '19',
            name: '@ThailandCCUnavPageCheck',
            path: '/th_th/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavThailand',
            country: 'Thailand',
        },
        {
            tcid: '20',
            name: '@SingaporeCCUnavPageCheck',
            path: '/sg/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavSingapore',
            country: 'Singapore',
        },
        {
            tcid: '21',
            name: '@PhilippinesCCUnavPageCheck',
            path: '/ph_fil/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavPhilippines',
            country: 'Philippines',
        },
        {
            tcid: '22',
            name: '@PhilippinesEnglishCCUnavPageCheck',
            path: '/ph_fil/creativecloud.html?georouting=off',
            tags: '@ccounavpagesanity @ccunavPhilippinesEnglish',
            country: 'Philippines English',
        }
    ]
}