module.exports = {
  name: 'Creative Cloud UNAV Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesCCUnavPageCheck',
      path: '/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavUnitedStates',
      buyNowUrl: 'https://www.adobe.com/creativecloud/plans.html?filter=acrobat&plan=individual&filter=acrobat',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyCCUnavPageCheck',
      path: '/de/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavGermany',
      buyNowUrl: 'https://www.adobe.com/de/creativecloud/plans.html',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceCCUnavPageCheck',
      path: '/fr/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavFrance',
      buyNowUrl: 'https://www.adobe.com/fr/creativecloud/plans.html',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyCCUnavPageCheck',
      path: '/it/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavItaly',
      buyNowUrl: 'https://www.adobe.com/it/creativecloud/plans.html',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomCCUnavPageCheck',
      path: '/uk/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavUnitedKingdom',
      buyNowUrl: 'https://www.adobe.com/uk/creativecloud/plans.html',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaCCUnavPageCheck',
      path: '/mena_ar/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavMiddleEastAndNorthAfrica',
      buyNowUrl: 'https://www.adobe.com/mena_ar/creativecloud/plans.html',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanCCUnavPageCheck',
      path: '/jp/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavJapan',
      buyNowUrl: 'https://www.adobe.com/jp/creativecloud/plans.html',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaCCUnavPageCheck',
      path: '/in/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavIndia',
      buyNowUrl: 'https://www.adobe.com/in/creativecloud/plans.html',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainCCUnavPageCheck',
      path: '/es/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavSpain',
      buyNowUrl: 'https://www.adobe.com/es/creativecloud/plans.html',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishCCUnavPageCheck',
      path: '/ca/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavCanadaEnglish',
      buyNowUrl: 'https://www.adobe.com/ca/creativecloud/plans.html?filter=acrobat&plan=individual&filter=acrobat',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaCCUnavPageCheck',
      path: '/kr/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavKorea',
      buyNowUrl: 'https://www.adobe.com/kr/creativecloud/plans.html',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchCCUnavPageCheck',
      path: '/ca_fr/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavCanadaFrench',
      buyNowUrl: 'https://www.adobe.com/ca_fr/creativecloud/plans.html?filter=acrobat&plan=individual&filter=acrobat',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandCCUnavPageCheck',
      path: '/pl/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavPoland',
      buyNowUrl: 'https://www.adobe.com/pl/creativecloud/plans.html?filter=acrobat&plan=individual&filter=acrobat',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoCCUnavPageCheck',
      path: '/mx/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavMexico',
      buyNowUrl: 'https://www.adobe.com/mx/creativecloud/plans.html',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaCCUnavPageCheck',
      path: '/au/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavAustralia',
      buyNowUrl: 'https://www.adobe.com/au/creativecloud/plans.html',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaCCUnavPageCheck',
      path: '/id_id/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavIndonesia',
      buyNowUrl: 'https://www.adobe.com/id_id/creativecloud/plans.html',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishCCUnavPageCheck',
      path: '/id_en/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavIndonesiaEnglish',
      buyNowUrl: 'https://www.adobe.com/id_en/creativecloud/plans.html',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyCCUnavPageCheck',
      path: '/tr/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavTurkey',
      buyNowUrl: 'https://www.adobe.com/tr/creativecloud/plans.html',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishCCUnavPageCheck',
      path: '/th_en/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavThailandEnglish',
      buyNowUrl: 'https://www.adobe.com/th_en/creativecloud/plans.html',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandCCUnavPageCheck',
      path: '/th_th/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavThailand',
      buyNowUrl: 'https://www.adobe.com/th_th/creativecloud/plans.html',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeCCUnavPageCheck',
      path: '/sg/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavSingapore',
      buyNowUrl: 'https://www.adobe.com/sg/creativecloud/plans.html',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippinesCCUnavPageCheck',
      path: '/ph_fil/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavPhilippines',
      buyNowUrl: 'https://www.adobe.com/ph_fil/creativecloud/plans.html',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippinesEnglishCCUnavPageCheck',
      path: '/ph_en/creativecloud.html?georouting=off',
      tags: '@ccounavpagesanity @ccunavPhilippinesEnglish',
      buyNowUrl: 'https://www.adobe.com/ph_en/creativecloud/plans.html',
      country: 'Philippines English',
    },
  ],
};
