module.exports = {
  name: 'documentcloud pages',
  features: [
    {
      tcid: '0',
      name: '@USDCAcrobat',
      path: '/acrobat.html',
      tags: '@DCSanity @USDCAcrobat-sanity',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@USDCSign',
      path: '/acrobat/business/sign.html',
      tags: '@DCSanity @USDCSign-sanity',
      country: 'United States',
    },
    {
      tcid: '2',
      name: '@UKDCAcrobat',
      path: '/uk/acrobat.html',
      tags: '@DCSanity @UKDCAcrobat-sanity',
      country: 'United kingdom',
    },
    {
      tcid: '3',
      name: '@FRDCActobat',
      path: '/fr/acrobat.html',
      tags: '@DCSanity @FRDCAcrobat-sanity',
      country: 'France',
    },
    {
      tcid: '4',
      name: '@DEDCSanity',
      path: '/de/acrobat.html',
      tags: '@DCSanity @DEDCAcrobat-sanity',
      country: 'German',
    },
    {
      tcid: '5',
      name: '@JPDCSanity',
      path: '/jp/acrobat.html',
      tags: '@DCSanity @JPDCAcrobat-sanity',
      country: 'Japanese',
    },
    {
      tcid: '6',
      name: '@SGDCSanity',
      path: '/sg/acrobat.html',
      tags: '@DCSanity @SGDCAcrobat-sanity',
      country: 'Singapore',
    },
    {
      tcid: '7',
      name: '@AUDCSanity',
      path: '/au/acrobat.html',
      tags: '@DCSanity @AUDCAcrobat-sanity',
      country: 'Australia',
    },
    {
      tcid: '8',
      name: '@IEDCSanity',
      path: '/ie/acrobat.html',
      tags: '@DCSanity @IEDCAcrobat-sanity',
      country: 'Ireland',
    },
    {
      tcid: '9',
      name: '@ESDCSanity',
      path: '/es/acrobat.html',
      tags: '@DCSanity @ESDCAcrobat-sanity',
      country: 'Espana',
    },
    {
      tcid: '10',
      name: '@DKDCSanity',
      path: '/dk/acrobat.html',
      tags: '@DCSanity @DKAcrobat-sanity',
      country: 'Denmark',
    },
    {
      tcid: '11',
      name: '@BEENDCSanity',
      path: '/be_en/acrobat.html',
      tags: '@DCSanity @BEENDCAcrobat-sanity',
      country: 'Belgium',
    },
    {
      tcid: '12',
      name: '@AFRICADCSanity',
      path: '/africa/acrobat.html',
      tags: '@DCSanity @AFRICADCAcrobat-sanity',
      country: 'Africa',
    },
    {
      tcid: '13',
      name: '@MXDCSanity',
      path: '/mx/acrobat.html',
      tags: '@DCSanity @MXDCAcrobat-sanity',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@LADCSanity',
      path: '/la/acrobat.html',
      tags: '@DCSanity @LADCAcrobat-sanity',
      country: 'Latinamerica',
    },
    {
      tcid: '15',
      name: '@CADCSanity',
      path: '/ca/acrobat.html',
      tags: '@DCSanity @CADCAcrobat-sanity',
      country: 'Canada',
    },
    {
      tcid: '16',
      name: '@HUDCSanity',
      path: '/hu/acrobat.html',
      tags: '@DCSanity @HUDCAcrobat-sanity',
      country: 'Hungary',
    },
    {
      tcid: '17',
      name: '@NLDCSanity',
      path: '/nl/acrobat.html',
      tags: '@DCSanity @NLDCAcrobat-sanity',
      country: 'Netherlands',
    },
    {
      tcid: '18',
      name: '@FIDCSanity',
      path: '/fi/acrobat.html',
      tags: '@DCSanity @FIDCAcrobat-sanity',
      country: 'Finland',
    },
    {
      tcid: '19',
      name: '@SEDCSanity',
      path: '/se/acrobat.html',
      tags: '@DCSanity @SEDCAcrobat-sanity',
      country: 'Sweden',
    },
    {
      tcid: '20',
      name: '@INDCSanity',
      path: '/in/acrobat.html',
      tags: '@DCSanity @INDCAcrobat-sanity',
      country: 'India',
    },
    {
      tcid: '21',
      name: '@NZDCSanity',
      path: '/nz/acrobat.html',
      tags: '@DCSanity @NZDCAcrobat-sanity',
      country: 'Newzeland',
    },
    {
      tcid: '22',
      name: '@KRDCSanity',
      path: '/kr/acrobat.html',
      tags: '@DCSanity @KRDCAcrobat-sanity',
      country: 'Korea',
    },
  ],
};
