module.exports = {
  name: 'Illustrator Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesillustratorPageCheck',
      path: '/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorUnitedStates',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyillustratorPageCheck',
      path: '/de/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceillustratorPageCheck',
      path: '/fr/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyillustratorPageCheck',
      path: '/it/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomillustratorPageCheck',
      path: '/uk/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaillustratorPageCheck',
      path: '/mena_ar/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanillustratorPageCheck',
      path: '/jp/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaillustratorPageCheck',
      path: '/in/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainillustratorPageCheck',
      path: '/es/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorSpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishillustratorPageCheck',
      path: '/ca/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorCanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaillustratorPageCheck',
      path: '/kr/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchillustratorPageCheck',
      path: '/ca_fr/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorCanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandillustratorPageCheck',
      path: '/pl/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorPoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoillustratorPageCheck',
      path: '/mx/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaillustratorPageCheck',
      path: '/au/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaillustratorPageCheck',
      path: '/id_id/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishillustratorPageCheck',
      path: '/id_en/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyillustratorPageCheck',
      path: '/tr/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorTurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishillustratorPageCheck',
      path: '/th_en/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandillustratorPageCheck',
      path: '/th_th/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeillustratorPageCheck',
      path: '/sg/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorSingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineillustratorPageCheck',
      path: '/ph_fil/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorPhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippineEnglishillustratorPageCheck',
      path: '/ph_en/products/illustrator.html?georouting=off#modal-hash',
      tags: '@illustratorpagesanity @illustratorPhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
