module.exports = {
  name: 'ostprices',
  features: [
    {
      tcid: '0',
      name: '@ost-currencyformat-price-buyemailcta',
      path: '/drafts/Automation-PW/OST-prices/marquee-price?georouting=off',
      envs: '@cc_live @adobe_stage',
      tags: '@cc @cc-ost @cc-pricewithcta',
    },
    {
      tcid: '1',
      name: '@ost-ccallapps-price-buysegmentcta',
      path: '/drafts/Automation-PW/OST-prices/cc-monty-year-ucv3?georouting=off',
      envs: '@cc_live @adobe_stage',
      tags: '@cc @cc-ost @cc-allappswithcta',
    },
    {
      tcid: '2',
      name: '@ost-student-price-buycta',
      path: '/drafts/Automation-PW/OST-prices/ste-prices?georouting=off',
      envs: '@cc_live @adobe_stage',
      tags: '@cc @cc-ost @cc-steprices',
    },
    {
      tcid: '3',
      name: '@ost-strike-throughprice-buycta',
      path: '/drafts/Automation-PW/OST-prices/strike-through-prices?georouting=off',
      envs: '@cc_live @adobe_stage',
      tags: '@cc @cc-ost @cc-strikethroughprice',
    },
    {
      tcid: '4',
      name: '@ost-month-year-prices-buycta',
      path: '/drafts/Automation-PW/OST-prices/photoshop-prices?georouting=off',
      envs: '@cc_live @adobe_stage',
      tags: '@cc @cc-ost @cc-montandyearprices',
    },
    {
      tcid: '5',
      name: '@ost-jp-currencyformat-price-buyemailcta',
      path: '/jp/drafts/Automation-PW/OST-prices/marquee-price?georouting=off',
      envs: '@cc_live @adobe_stage',
      tags: '@cc @cc-ost @cc-jp-pricewithcta',
    },
    {
      tcid: '6',
      name: '@ost-jp-ccallapps-price-buysegmentcta',
      path: '/jp/drafts/Automation-PW/OST-prices/cc-monty-year-ucv3?georouting=off',
      envs: '@cc_live @adobe_stage',
      tags: '@cc @cc-ost @cc-jp-allappswithcta',
    },
    {
      tcid: '7',
      name: '@ost-jp-student-price-buycta',
      path: '/jp/drafts/Automation-PW/OST-prices/ste-prices?georouting=off',
      envs: '@cc_live @adobe_stage',
      tags: '@cc @cc-ost @cc-jp-steprices',
    },
    {
      tcid: '8',
      name: '@ost-jp-strike-throughprice-buycta',
      path: '/jp/drafts/Automation-PW/OST-prices/strike-through-prices?georouting=off',
      envs: '@cc_live @adobe_stage',
      tags: '@cc @cc-ost @cc-jp-strikethroughprice',
    },
    {
      tcid: '9',
      name: '@ost-jp-month-year-prices-buycta',
      path: '/jp/drafts/Automation-PW/OST-prices/photoshop-prices?georouting=off',
      envs: '@cc_live @adobe_stage',
      tags: '@cc @cc-ost @cc-jp-monthyearprices',
    },
  ],
};
