module.exports = {
  name: 'productionsanity',
  features: [
    {
      tcid: '0',
      name: '@creativecloudhomepage',
      path: '/creativecloud.html?georouting=off',
      tags: '@cc @cc-prodsanity @cc-homepagesanity',
      commerceurl: 'https://commerce.adobe.com/store/commitment?items%5B0%5D%5Bid%5D=81DE7D1C91A201AB690BC4741B32F0C0&cli=adobe_com&ctx=fp&co=US&lang=en',
    },
    {
      tcid: '1',
      name: '@aftereffectsproductpage',
      path: '/products/aftereffects.html?georouting=off',
      tags: '@cc @cc-prodsanity @cc-aftereffectssanity',
      url: 'https://www.adobe.com/creativecloud/plans.html?filter=video-audio&plan=individual',
    },
    {
      tcid: '2',
      name: '@ccpricingpage',
      path: '/creativecloud/campaign/pricing.html?georouting=off',
      tags: '@cc @cc-prodsanity @cc-pricingpagesanity',
    },
    {
      tcid: '3',
      name: '@illustratorproductpage',
      path: '/products/illustrator.html?georouting=off',
      tags: '@cc @cc-prodsanity @cc-illustratorsanity',
      url: 'https://www.adobe.com/products/illustrator.html?georouting=off#marqueectatwp',
    },
    {
      tcid: '4',
      name: '@CCTproductpage',
      path: '/creativecloud/business/teams/resources/how-to/5-diy-marketing-strategies.html?georouting=off',
      tags: '@cc @cc-prodsanity @cc-CCTpagesanity',
      url: 'https://www.adobe.com/creativecloud/business-plans.html?plan=team&step=2',
    },
    {
      tcid: '5',
      name: '@CCmodelprices',
      path: '/products/premiere.html#marqueectatwp',
      tags: '@cc @cc-prodsanity @cc-CCpricemodelsanity',
    },
    {
      tcid: '6',
      name: '@CCUKpagesanitycheck',
      path: '/uk/creativecloud/animation/discover.html?georouting=off',
      tags: '@cc @cc-prodsanity @cc-CCUKPagesanity',
      url: 'https://www.adobe.com/uk/creativecloud/animation/discover/animation.html',
    },
    {
      tcid: '7',
      name: '@CCDEpagesanitycheck',
      path: '/de/creativecloud/tools.html?georouting=off',
      tags: '@cc @cc-prodsanity @cc-CCDEPagesanity',
      url: 'https://www.adobe.com/de/creativecloud/plans.html',
    },
    {
      tcid: '8',
      name: '@CCJPpagesanitycheck',
      path: '/jp/creativecloud/file-types/image.html?georouting=off',
      tags: '@cc @cc-prodsanity @cc-CCJPPagesanity',
      url: 'https://www.adobe.com/jp/creativecloud/plans.html',
    },
    {
      tcid: '9',
      name: '@CCFRpagesanitycheck',
      path: '/fr/creativecloud/animation/discover/claymation.html?georouting=off',
      tags: '@cc @cc-prodsanity @cc-CCFRPagesanity',
      marqueelink: 'https://www.adobe.com/fr/creativecloud/animation-software.html',
    },
  ],
};
