module.exports = {
  name: 'Quiz Recommender Blocks',
  features: [
    {
      tcid: '10',
      name: '@quiz single template',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-template-single @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '11',
      name: '@quiz double template',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-template-double @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '12',
      name: '@quiz triple template',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-template-triple @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '20',
      name: '@quiz single flagship photo',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-single-photo @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '21',
      name: '@quiz single flagship video',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-single-video @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '22',
      name: '@quiz single flagship design',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-single-design @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '23',
      name: '@quiz single flagship illustration',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-single-illustration @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '24',
      name: '@quiz single flagship pdf',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-single-pdf @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '30',
      name: '@quiz double flagship photo video',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-double-photo-video @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '31',
      name: '@quiz double flagship photo design',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-double-photo-design @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '32',
      name: '@quiz double flagship photo illustration',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-double-photo-illustration @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '33',
      name: '@quiz double flagship photo pdf',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-double-photo-pdf @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '34',
      name: '@quiz double flagship video design',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-double-video-design @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '35',
      name: '@quiz double flagship video illustration',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-double-video-illustration @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '36',
      name: '@quiz double flagship video pdf',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-double-video-pdf @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '37',
      name: '@quiz double flagship design illustration',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-double-design-illustration @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '38',
      name: '@quiz double flagship design pdf',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-double-design-pdf @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '39',
      name: '@quiz double flagship illustration pdf',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-double-illustration-pdf @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '40',
      name: '@quiz triple flagship photo video design',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-triple-photo-video-design @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '41',
      name: '@quiz triple flagship photo video illustration',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-triple-photo-video-illustration @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '42',
      name: '@quiz triple flagship photo video pdf',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-triple-photo-video-pdf @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '43',
      name: '@quiz triple flagship video design illustration',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-triple-video-design-illustration @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '44',
      name: '@quiz triple flagship video design pdf',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-triple-video-design-pdf @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '45',
      name: '@quiz triple flagship design illustration pdf',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-flagship-triple-design-illustration-pdf @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '50',
      name: '@quiz single 3D',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-single-3D @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '51',
      name: '@quiz double 3D',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-double-3D @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
    {
      tcid: '52',
      name: '@quiz triple 3D',
      path: '/creativecloud/plan-recommender/quiz',
      tags: '@cc @uar-quiz-dynamic-triple-3D @uar-quiz-dynamic',
      data: 'creativecloud/plan-recommender/strings.json',
    },
  ],
};
