module.exports = {
  name: 'Quiz Recommender Blocks',
  features: [
    {
      tcid: '1',
      name: '@quiz single template',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@quiz-single-template @quiz-static',
      data: 'data/cc/quiz/quiz-single-template.yml',
      envs: '@adobe_prod @adobe_stage',
    },
    {
      tcid: '2',
      name: '@quiz double template',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@quiz-double-template @quiz-static',
      data: 'data/cc/quiz/quiz-double-template.yml',
      envs: '@adobe_prod @adobe_stage',
    },
    {
      tcid: '3',
      name: '@quiz triple template',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@quiz-triple-template @quiz-static',
      data: 'data/cc/quiz/quiz-triple-template.yml',
      envs: '@adobe_prod @adobe_stage',
    },
    {
      tcid: '4',
      name: '@quiz single flagship photo',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@quiz-single-flagship-photo @quiz-static',
      data: 'data/cc/quiz/quiz-single-flagship-photo.yml',
      envs: '@adobe_prod @adobe_stage',
    },
    {
      tcid: '5',
      name: '@quiz single flagship video',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@quiz-single-flagship-video @quiz-static',
      data: 'data/cc/quiz/quiz-single-flagship-video.yml',
      envs: '@adobe_prod @adobe_stage',
    },
    {
      tcid: '6',
      name: '@quiz double flagship design illustration',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@quiz-double-flagship-design-illustration @quiz-static',
      data: 'data/cc/quiz/quiz-double-flagship-design-illustration.yml',
      envs: '@adobe_prod @adobe_stage',
    },
    {
      tcid: '7',
      name: '@quiz double flagship photo illustration',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@quiz-double-flagship-photo-illustration @quiz-static',
      data: 'data/cc/quiz/quiz-double-flagship-photo-illustration.yml',
      envs: '@adobe_prod @adobe_stage',
    },
    {
      tcid: '8',
      name: '@quiz triple flagship photo video pdf',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@quiz-triple-flagship-photo-video-pdf @quiz-static',
      data: 'data/cc/quiz/quiz-triple-flagship-photo-video-pdf.yml',
      envs: '@adobe_prod @adobe_stage',
    },
    {
      tcid: '9',
      name: '@quiz single 3D',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@quiz-single-3D @quiz-static',
      data: 'data/cc/quiz/quiz-single-3D.yml',
      envs: '@adobe_prod @adobe_stage',
    },
  ],
};
