module.exports = {
  name: 'Aside Block',
  features: [
    {
      name: '@Aside-Small',
      path: '/drafts/nala/blocks/aside/aside-small',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-small, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Medium',
      path: '/drafts/nala/blocks/aside/aside-medium',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-medium, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Large',
      path: '/drafts/nala/blocks/aside/aside-large',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-large, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Split-Small-Dark',
      path: '/drafts/nala/blocks/aside/aside-split-small-dark',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-split-small-dark, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Split-Small-Half-Dark',
      path: '/drafts/nala/blocks/aside/aside-split-small-half-dark',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-split-small-half-dark, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Split-Medium',
      path: '/drafts/nala/blocks/aside/aside-split-medium',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-split-medium, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Split-Medium-Half',
      path: '/drafts/nala/blocks/aside/aside-split-medium-half',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-split-medium, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Split-Large',
      path: '/drafts/nala/blocks/aside/aside-split-large',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-split-large, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Split-Large-Half-Dark',
      path: '/drafts/nala/blocks/aside/aside-split-large-half-dark',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-split-large-half-dark, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Inline',
      path: '/drafts/nala/blocks/aside/aside-inline',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-inline, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Inline-Dark',
      path: '/drafts/nala/blocks/aside/aside-inline-dark',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-inline-dark, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Notif-Extra-Small-Dark',
      path: '/drafts/nala/blocks/aside/aside-notification-extrasmall-dark',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-notif-extra-small-dark, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Notif-Small',
      path: '/drafts/nala/blocks/aside/aside-notification-small',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-notif-small, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Notif-Medium',
      path: '/drafts/nala/blocks/aside/aside-notification-medium',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-notif-medium, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Notif-Medium-Center',
      path: '/drafts/nala/blocks/aside/aside-notification-medium-center',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-notif-medium-center, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Notif-Large',
      path: '/drafts/nala/blocks/aside/aside-notification-large',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-notif-large, @smoke, @regression @milo',
    },
    {
      name: '@Aside-Notif-Large-Center',
      path: '/drafts/nala/blocks/aside/aside-notification-large-center',
      browserParams: '?hideGeorouting=on',
      tags: '@aside, @aside-notif-large-center, @smoke, @regression @milo',
    },
  ],
};
