module.exports = {
  name: 'Creative Cloud UNAV Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesCCUtabiPadSanity',
      path: '/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuUnitedStates',
      buyNowUrl: '/creativecloud/plans.html?filter=acrobat&plan=individual&filter=acrobat',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyCCUtabiPadSanity',
      path: '/de/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuGermany',
      buyNowUrl: '/de/creativecloud/plans.html',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceCCUtabiPadSanity',
      path: '/fr/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuFrance',
      buyNowUrl: '/fr/creativecloud/plans.html',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyCCUtabiPadSanity',
      path: '/it/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuItaly',
      buyNowUrl: '/it/creativecloud/plans.html',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomCCUtabiPadSanity',
      path: '/uk/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuUnitedKingdom',
      buyNowUrl: '/uk/creativecloud/plans.html',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaCCUtabiPadSanity',
      path: '/mena_ar/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuMiddleEastAndNorthAfrica',
      buyNowUrl: '/mena_ar/creativecloud/plans.html',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanCCUtabiPadSanity',
      path: '/jp/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuJapan',
      buyNowUrl: '/jp/creativecloud/plans.html',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaCCUtabiPadSanity',
      path: '/in/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuIndia',
      buyNowUrl: '/in/creativecloud/plans.html',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainCCUtabiPadSanity',
      path: '/es/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuSpain',
      buyNowUrl: '/es/creativecloud/plans.html',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishCCUtabiPadSanity',
      path: '/ca/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuCanadaEnglish',
      buyNowUrl: '/ca/creativecloud/plans.html',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaCCUtabiPadSanity',
      path: '/kr/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuKorea',
      buyNowUrl: '/kr/creativecloud/plans.html',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchCCUtabiPadSanity',
      path: '/ca_fr/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuCanadaFrench',
      buyNowUrl: '/ca_fr/creativecloud/plans.html',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandCCUtabiPadSanity',
      path: '/pl/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuPoland',
      buyNowUrl: '/pl/creativecloud/plans.html',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoCCUtabiPadSanity',
      path: '/mx/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuMexico',
      buyNowUrl: '/mx/creativecloud/plans.html',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaCCUtabiPadSanity',
      path: '/au/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuAustralia',
      buyNowUrl: '/au/creativecloud/plans.html',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaCCUtabiPadSanity',
      path: '/id_id/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuIndonesia',
      buyNowUrl: '/id_id/creativecloud/plans.html',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishCCUtabiPadSanity',
      path: '/id_en/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuIndonesiaEnglish',
      buyNowUrl: '/id_en/creativecloud/plans.html',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyCCUtabiPadSanity',
      path: '/tr/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuTurkey',
      buyNowUrl: '/tr/creativecloud/plans.html',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishCCUtabiPadSanity',
      path: '/th_en/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuThailandEnglish',
      buyNowUrl: '/th_en/creativecloud/plans.html',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandCCUtabiPadSanity',
      path: '/th_th/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuThailand',
      buyNowUrl: '/th_th/creativecloud/plans.html',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeCCUtabiPadSanity',
      path: '/sg/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuSingapore',
      buyNowUrl: '/sg/creativecloud/plans.html',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippinesCCUtabiPadSanity',
      path: '/ph_fil/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuPhilippines',
      buyNowUrl: '/ph_fil/creativecloud/plans.html',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippinesEnglishCCUtabiPadSanity',
      path: '/ph_en/creativecloud.html?georouting=off',
      tags: '@tabipadccounavanity @tabipadccuPhilippinesEnglish',
      buyNowUrl: '/ph_en/creativecloud/plans.html',
      country: 'Philippines English',
    },
  ],
};
