module.exports = {
  name: 'Creative Cloud Enterprise Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesCCEtabiPadPageCheck',
      path: '/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @ccetabipadUnitedStatesPage',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyCCEtabiPadPageCheck',
      path: '/de/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @ccetabipadGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceCCEtabiPadPageCheck',
      path: '/fr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyCCEtabiPadPageCheck',
      path: '/it/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomCCEtabiPadPageCheck',
      path: '/uk/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaCCEtabiPadPageCheck',
      path: '/mena_ar/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanCCEtabiPadPageCheck',
      path: '/jp/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaCCEtabiPadPageCheck',
      path: '/in/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainCCEtabiPadPageCheck',
      path: '/es/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadSpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishCCEtabiPadPageCheck',
      path: '/ca/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadCanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaCCEtabiPadPageCheck',
      path: '/kr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchCCEtabiPadPageCheck',
      path: '/ca_fr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadCanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandCCEtabiPadPageCheck',
      path: '/pl/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadPoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoCCEtabiPadPageCheck',
      path: '/mx/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaCCEtabiPadPageCheck',
      path: '/au/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaCCEtabiPadPageCheck',
      path: '/id_id/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishCCEtabiPadPageCheck',
      path: '/id_en/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyCCEtabiPadPageCheck',
      path: '/tr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadTurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishCCEtabiPadPageCheck',
      path: '/th_en/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandCCEtabiPadPageCheck',
      path: '/th_th/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeCCEtabiPadPageCheck',
      path: '/sg/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadSingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineCCEtabiPadPageCheck',
      path: '/ph_fil/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadPhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippineEnglishCCEtabiPadPageCheck',
      path: '/ph_en/creativecloud/business/enterprise.html?georouting=off',
      tags: '@ccetabipadpagesanity @CCEtabipadPhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
