module.exports = {
  name: 'Illustrator Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesTabiPadIllustratorPageCheck',
      path: '/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorUnitedStates',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyTabiPadIllustratorPageCheck',
      path: '/de/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceTabiPadIllustratorPageCheck',
      path: '/fr/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyTabiPadIllustratorPageCheck',
      path: '/it/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomTabiPadIllustratorPageCheck',
      path: '/uk/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaTabiPadIllustratorPageCheck',
      path: '/mena_ar/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanTabiPadIllustratorPageCheck',
      path: '/jp/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaTabiPadIllustratorPageCheck',
      path: '/in/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainTabiPadIllustratorPageCheck',
      path: '/es/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorSpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishTabiPadIllustratorPageCheck',
      path: '/ca/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorCanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaTabiPadIllustratorPageCheck',
      path: '/kr/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchTabiPadIllustratorPageCheck',
      path: '/ca_fr/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorCanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandTabiPadIllustratorPageCheck',
      path: '/pl/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorPoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoTabiPadIllustratorPageCheck',
      path: '/mx/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaTabiPadIllustratorPageCheck',
      path: '/au/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaTabiPadIllustratorPageCheck',
      path: '/id_id/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishTabiPadIllustratorPageCheck',
      path: '/id_en/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyTabiPadIllustratorPageCheck',
      path: '/tr/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorTurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishTabiPadIllustratorPageCheck',
      path: '/th_en/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandTabiPadIllustratorPageCheck',
      path: '/th_th/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeTabiPadIllustratorPageCheck',
      path: '/sg/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorSingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineTabiPadIllustratorPageCheck',
      path: '/ph_fil/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorPhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippineEnglishTabiPadIllustratorPageCheck',
      path: '/ph_en/products/illustrator.html?georouting=off#modal-hash',
      tags: '@tabiPadIllustratorSanity @tabiPadIllustratorPhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
