module.exports = {
  name: 'Creative Cloud Teams Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesMobileCCTPageCheck',
      path: '/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTUnitedStatesPage',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyMobileCCTPageCheck',
      path: '/de/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTGermanyPage',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceMobileCCTPageCheck',
      path: '/fr/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTFrancePage',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyMobileCCTPageCheck',
      path: '/it/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTItalyPage',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomMobileCCTPageCheck',
      path: '/uk/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTUnitedKingdomPage',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaMobileCCTPageCheck',
      path: '/mena_ar/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTMiddleEastAndNorthAfricaPage',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanMobileCCTPageCheck',
      path: '/jp/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTJapanPage',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaMobileCCTPageCheck',
      path: '/in/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTIndiaPage',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainMobileCCTPageCheck',
      path: '/es/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTSpainPage',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishMobileCCTPageCheck',
      path: '/ca/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTCanadaEnglishPage',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaMobileCCTPageCheck',
      path: '/kr/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTKoreaPage',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchMobileCCTPageCheck',
      path: '/ca_fr/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTCanadaFrenchPage',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandMobileCCTPageCheck',
      path: '/pl/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTPolandPage',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoMobileCCTPageCheck',
      path: '/mx/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTMexicoPage',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaMobileCCTPageCheck',
      path: '/au/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTAustraliaPage',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaMobileCCTPageCheck',
      path: '/id_id/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTIndonesiaPage',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishMobileCCTPageCheck',
      path: '/id_en/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTIndonesiaEnglishPage',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyMobileCCTPageCheck',
      path: '/tr/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTTurkeyPage',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishMobileCCTPageCheck',
      path: '/th_en/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTThailandEnglishPage',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandMobileCCTPageCheck',
      path: '/th_th/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTThailandPage',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeMobileCCTPageCheck',
      path: '/sg/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTSingaporePage',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineMobileCCTPageCheck',
      path: '/ph_fil/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTPhilippinesPage',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippinesEnglishMobileCCTPageCheck',
      path: '/ph_en/creativecloud/business/teams.html?georouting=off&mep=off',
      tags: '@mobileCCTpagesanity @mobileCCTPhilippinesEnglishPage',
      country: 'Philippines English',
    },
  ],
};
