module.exports = {
  name: 'Illustrator Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesMobileillustratorPageCheck',
      path: '/products/illustrator.html?georouting=off#modal-hash',
      tags: '@mobileIllustratorSanity @mobileIllustratorUnitedStates',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyMobileillustratorPageCheck',
      path: '/de/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceMobileillustratorPageCheck',
      path: '/fr/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyMobileillustratorPageCheck',
      path: '/it/products/illustrator.html?georouting=off#modal-hash',
      tags: '@mobileIllustratorSanity @mobileIllustratorItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomMobileillustratorPageCheck',
      path: '/uk/products/illustrator.html?georouting=off#modal-hash',
      tags: '@mobileIllustratorSanity @mobileIllustratorUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaMobileillustratorPageCheck',
      path: '/mena_ar/products/illustrator.html?georouting=off#modal-hash',
      tags: '@mobileIllustratorSanity @mobileIllustratorMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanMobileillustratorPageCheck',
      path: '/jp/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaMobileillustratorPageCheck',
      path: '/in/products/illustrator.html?georouting=off#modal-hash',
      tags: '@mobileIllustratorSanity @mobileIllustratorIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainMobileillustratorPageCheck',
      path: '/es/products/illustrator.html?georouting=off#modal-hash',
      tags: '@mobileIllustratorSanity @mobileIllustratorSpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishMobileillustratorPageCheck',
      path: '/ca/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorCanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaMobileillustratorPageCheck',
      path: '/kr/products/illustrator.html?georouting=off#modal-hash',
      tags: '@mobileIllustratorSanity @mobileIllustratorKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchMobileillustratorPageCheck',
      path: '/ca_fr/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorCanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandMobileillustratorPageCheck',
      path: '/pl/products/illustrator.html?georouting=off#modal-hash',
      tags: '@mobileIllustratorSanity @mobileIllustratorPoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoMobileillustratorPageCheck',
      path: '/mx/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaMobileillustratorPageCheck',
      path: '/au/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaMobileillustratorPageCheck',
      path: '/id_id/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishMobileillustratorPageCheck',
      path: '/id_en/products/illustrator.html?georouting=off#modal-hash',
      tags: '@mobileIllustratorSanity @mobileIllustratorIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyMobileillustratorPageCheck',
      path: '/tr/products/illustrator.html?georouting=off#modal-hash',
      tags: '@mobileIllustratorSanity @mobileIllustratorTurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishMobileillustratorPageCheck',
      path: '/th_en/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandMobileillustratorPageCheck',
      path: '/th_th/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeMobileillustratorPageCheck',
      path: '/sg/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorSingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineMobileillustratorPageCheck',
      path: '/ph_fil/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorPhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippineEnglishMobileillustratorPageCheck',
      path: '/ph_en/products/illustrator.html?georouting=off',
      tags: '@mobileIllustratorSanity @mobileIllustratorPhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
