module.exports = {
  name: 'Photoshop Page Sanity',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesMobilePhotoshopSanityPageCheck',
      path: '/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityUnitedStatesPage',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyMobilePhotoshopSanityPageCheck',
      path: '/de/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityGermanyPage',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceMobilePhotoshopSanityPageCheck',
      path: '/fr/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityFrancePage',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyMobilePhotoshopSanityPageCheck',
      path: '/it/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityItalyPage',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomMobilePhotoshopSanityPageCheck',
      path: '/uk/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityUnitedKingdomPage',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaMobilePhotoshopSanityPageCheck',
      path: '/mena_ar/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityMiddleEastAndNorthAfricaPage',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanMobilePhotoshopSanityPageCheck',
      path: '/jp/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityJapanPage',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaMobilePhotoshopSanityPageCheck',
      path: '/in/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityIndiaPage',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainMobilePhotoshopSanityPageCheck',
      path: '/es/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanitySpainPage',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishMobilePhotoshopSanityPageCheck',
      path: '/ca/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityCanadaEnglishPage',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaMobilePhotoshopSanityPageCheck',
      path: '/kr/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityKoreaPage',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchMobilePhotoshopSanityPageCheck',
      path: '/ca_fr/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityCanadaFrenchPage',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandMobilePhotoshopSanityPageCheck',
      path: '/pl/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityPolandPage',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoMobilePhotoshopSanityPageCheck',
      path: '/mx/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityMexicoPage',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaMobilePhotoshopSanityPageCheck',
      path: '/au/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityAustraliaPage',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaMobilePhotoshopSanityPageCheck',
      path: '/id_id/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityIndonesiaPage',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishMobilePhotoshopSanityPageCheck',
      path: '/id_en/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityIndonesiaEnglishPage',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyMobilePhotoshopSanityPageCheck',
      path: '/tr/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityTurkeyPage',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishMobilePhotoshopSanityPageCheck',
      path: '/th_en/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityThailandEnglishPage',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandMobilePhotoshopSanityPageCheck',
      path: '/th_th/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityThailandPage',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeMobilePhotoshopSanityPageCheck',
      path: '/sg/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanitySingaporePage',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineMobilePhotoshopSanityPageCheck',
      path: '/ph_fil/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityPhilippinesPage',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippinesEnglishMobilePhotoshopSanityPageCheck',
      path: '/ph_en/products/photoshop.html?georouting=off&mep=off',
      tags: '@mobilePhotoshopSanitypagesanity @mobilePhotoshopSanityPhilippinesEnglishPage',
      country: 'Philippines English',
    },
  ],
};
