module.exports = {
  name: 'Creative Cloud Enterprise Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesMobileCCEPageCheck',
      path: '/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEUnitedStatesPage',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyMobileCCEPageCheck',
      path: '/de/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceMobileCCEPageCheck',
      path: '/fr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyMobileCCEPageCheck',
      path: '/it/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomMobileCCEPageCheck',
      path: '/uk/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaMobileCCEPageCheck',
      path: '/mena_ar/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanMobileCCEPageCheck',
      path: '/jp/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaMobileCCEPageCheck',
      path: '/in/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainMobileCCEPageCheck',
      path: '/es/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCESpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishMobileCCEPageCheck',
      path: '/ca/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCECanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaMobileCCEPageCheck',
      path: '/kr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchMobileCCEPageCheck',
      path: '/ca_fr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCECanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandMobileCCEPageCheck',
      path: '/pl/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEPoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoMobileCCEPageCheck',
      path: '/mx/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaMobileCCEPageCheck',
      path: '/au/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaMobileCCEPageCheck',
      path: '/id_id/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishMobileCCEPageCheck',
      path: '/id_en/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyMobileCCEPageCheck',
      path: '/tr/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCETurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishMobileCCEPageCheck',
      path: '/th_en/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandMobileCCEPageCheck',
      path: '/th_th/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeMobileCCEPageCheck',
      path: '/sg/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCESingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineMobileCCEPageCheck',
      path: '/ph_fil/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEPhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippineEnglishMobileCCEPageCheck',
      path: '/ph_en/creativecloud/business/enterprise.html?georouting=off',
      tags: '@mobileCCEPageSanity @mobileCCEPhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
