module.exports = {
  name: 'Mobile Creative Cloud Unav Page',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesMobileCCUnavPageCheck',
      path: '/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavUnitedStates',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyMobileCCUnavPageCheck',
      path: '/de/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceMobileCCUnavPageCheck',
      path: '/fr/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyMobileCCUnavPageCheck',
      path: '/it/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomMobileCCUnavPageCheck',
      path: '/uk/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaMobileCCUnavPageCheck',
      path: '/mena_ar/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanMobileCCUnavPageCheck',
      path: '/jp/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaMobileCCUnavPageCheck',
      path: '/in/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainMobileCCUnavPageCheck',
      path: '/es/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavSpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishMobileCCUnavPageCheck',
      path: '/ca/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavCanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaMobileCCUnavPageCheck',
      path: '/kr/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchMobileCCUnavPageCheck',
      path: '/ca_fr/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavCanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandMobileCCUnavPageCheck',
      path: '/pl/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavPoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoMobileCCUnavPageCheck',
      path: '/mx/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaMobileCCUnavPageCheck',
      path: '/au/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaMobileCCUnavPageCheck',
      path: '/id_id/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishMobileCCUnavPageCheck',
      path: '/id_en/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyMobileCCUnavPageCheck',
      path: '/tr/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavTurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishMobileCCUnavPageCheck',
      path: '/th_en/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandMobileCCUnavPageCheck',
      path: '/th_th/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeMobileCCUnavPageCheck',
      path: '/sg/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavSingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippinesMobileCCUnavPageCheck',
      path: '/ph_fil/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavPhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippinesEnglishMobileCCUnavPageCheck',
      path: '/ph_en/creativecloud.html?georouting=off',
      tags: '@mobileCCOUnavPageSanity @mobileCCUnavPhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
