module.exports = {
  name: 'AdobeHomePage',
  features: [
    {
      tcid: '0',
      name: '@UnitedStatesMobileHomePageCheck',
      path: '/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageUnitedStates',
      country: 'United States',
    },
    {
      tcid: '1',
      name: '@GermanyMobileHomePageCheck',
      path: '/de/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FranceMobileHomePageCheck',
      path: '/fr/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyMobileHomePageCheck',
      path: '/it/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomMobileHomePageCheck',
      path: '/uk/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaMobileHomePageCheck',
      path: '/mena_ar/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanMobileHomePageCheck',
      path: '/jp/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaMobileHomePageCheck',
      path: '/in/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainMobileHomePageCheck',
      path: '/es/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageSpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishMobileHomePageCheck',
      path: '/ca/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageCanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaMobileHomePageCheck',
      path: '/kr/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchMobileHomePageCheck',
      path: '/ca_fr/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageCanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandMobileHomePageCheck',
      path: '/pl/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePagePoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoMobileHomePageCheck',
      path: '/mx/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaMobileHomePageCheck',
      path: '/au/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaMobileHomePageCheck',
      path: '/id_id/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishMobileHomePageCheck',
      path: '/id_en/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyMobileHomePageCheck',
      path: '/tr/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageTurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishMobileHomePageCheck',
      path: '/th_en/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandMobileHomePageCheck',
      path: '/th_th/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporeMobileHomePageCheck',
      path: '/sg/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePageSingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippineMobileHomePageCheck',
      path: '/ph_fil/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePagePhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippineEnglishMobileHomePageCheck',
      path: '/ph_en/?georouting=off',
      tags: '@mobileHomePageSanity @mobileHomePagePhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
