module.exports = {
  name: 'Important Express pages',
  features: [
    {
      tcid: '0',
      name: '@express-imp-pages',
      path: [
        '/express/',
        '/express/create/story/instagram',
        '/express/create/video/instagram/reel',
        '/express/create/post/instagram',
        '/express/create/video/tiktok',
        '/express/create/story/facebook',
        '/express/create/post/facebook',
        '/express/create/video/youtube',
        '/express/create/thumbnail/youtube',
        '/express/create/banner/youtube',
        '/express/create/meme',
        '/express/create/poster',
        '/express/create/brochure',
        '/express/create/invitation',
        '/express/create/menu',
        '/express/create/card',
        '/express/create/certificate',
        '/express/create/resume',
        '/express/create/invoice',
        '/express/feature/image/qr-code-generator',
        '/express/create/print/flyer',
        '/express/create/print/poster',
        '/express/create/print/card',
        '/express/create/print/invitation',
        '/express/create/print/business-card',
        '/express/create/print/t-shirt',
        '/express/print',
        '/express/feature/content-scheduler',
        '/express/create/business-card',
        '/express/create/flyer',
        '/express/create/logo',
        '/express/create/advertisement',
        '/express/create/photo-collage',
        '/express/create/presentation',
        '/express/create/profile-picture',
        '/express/create',
        '/express/feature/image/editor',
        '/express/feature/video/editor',
        '/express/templates',
        '/express/feature/image/remove-background',
        '/express/feature/image/resize',
        '/express/feature/image/convert/png-to-jpg',
        '/express/feature/image/convert/jpg-to-png',
        '/express/feature/image/convert/jpg-to-svg',
        '/express/feature/image/crop',
        '/express/feature/video/convert/video-to-gif',
        '/express/feature/video/crop',
        '/express/feature/video/trim',
        '/express/feature/video/resize',
        '/express/feature/video/merge',
        '/express/feature/video/convert/mp4',
        '/express/feature/video/animate/audio',
        '/express/feature/video/add-caption',
        '/express/feature',
        '/express/feature/video/remove-background',
        '/express/business/teams',
        '/express/business',
        '/express/nonprofits',
        '/express/entitled',
        '/express/business#sales-contact-form-1',
        '/express/#open-jarvis-chat',
        '/express/learn/students',
        '/express/pricing',

      ],
      tags: '@regression @express',
    },
  ],
};
