module.exports = {
  name: 'Important Express pages',
  features: [
    {
      tcid: '0',
      name: '@express-imp-pages',
      path: [
        '/',
        '/create/story/instagram',
        '/create/video/instagram/reel',
        '/create/post/instagram',
        '/create/video/tiktok',
        '/create/story/facebook',
        '/create/post/facebook',
        '/create/video/youtube',
        '/create/thumbnail/youtube',
        '/create/banner/youtube',
        '/create/meme',
        '/create/poster',
        '/create/brochure',
        '/create/invitation',
        '/create/menu',
        '/create/card',
        '/create/certificate',
        '/create/resume',
        '/create/invoice',
        '/feature/image/qr-code-generator',
        '/create/print/flyer',
        '/create/print/poster',
        '/create/print/card',
        '/create/print/invitation',
        '/create/print/business-card',
        '/create/print/t-shirt',
        '/print',
        '/feature/content-scheduler',
        '/create/business-card',
        '/create/flyer',
        '/create/logo',
        '/create/advertisement',
        '/create/photo-collage',
        '/create/presentation',
        '/create/profile-picture',
        '/create',
        '/feature/image/editor',
        '/feature/video/editor',
        '/templates',
        '/feature/image/remove-background',
        '/feature/image/resize',
        '/feature/image/convert/png-to-jpg',
        '/feature/image/convert/jpg-to-png',
        '/feature/image/convert/jpg-to-svg',
        '/feature/image/crop',
        '/feature/video/convert/video-to-gif',
        '/feature/video/crop',
        '/feature/video/trim',
        '/feature/video/resize',
        '/feature/video/merge',
        '/feature/video/convert/mp4',
        '/feature/video/animate/audio',
        '/feature/video/add-caption',
        '/feature',
        '/feature/video/remove-background',
        '/business/teams',
        '/business',
        '/nonprofits',
        '/entitled',
        '/business#sales-contact-form-1',
        '/#open-jarvis-chat',
        '/learn/students',
        '/pricing',

      ],
      tags: '@regression @express',
    },
  ],
};
