module.exports = {
  FeatureName: 'DX Sign In Flow',
  features: [
    {
      tcid: '1',
      name: '@login-redirect-to-protected-home',
      testId: '@MWPW-140197',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/public-page',
      tags: '@dx-signin @regression @login @nopr',
      data: {
        partnerLevel: 'spp-platinum:',
        expectedProtectedURL: '/solutionpartners/drafts/automation/regression/protected-home',
        expectedPublicURL: '/solutionpartners/drafts/automation/regression/public-page',
      },
    },
    {
      tcid: '2',
      name: '@login-no-redirection-public-news',
      testId: '@MWPW-140198 @MWPW-140201',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/partner-news',
      tags: '@dx-signin @regression @login @nopr',
      data: {
        partnerLevel: 'spp-gold:',
        expectedToSeeInURL: '/solutionpartners/drafts/automation/regression/partner-news',
      },
    },
    {
      tcid: '3',
      name: '@login-accessing-public-home-page-with-member-user-logged-in-to-adobe',
      testId: '@MWPW-140202',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/public-page',
      baseURL: 'https://www.stage.adobe.com/partners.html',
      tags: '@dx-signin @regression @login @nopr',
      data: {
        partnerLevel: 'spp-community:',
        expectedProtectedURL: '/solutionpartners/drafts/automation/regression/protected-home',
      },
    },
    {
      tcid: '4',
      name: '@login-accessing-restricted-home-page-with-member-user-logged-in-to-adobe',
      testId: '@MWPW-140203',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/public-page',
      baseURL: 'https://www.stage.adobe.com/partners.html',
      tags: '@dx-signin @regression @login @nopr',
      data: {
        partnerLevel: 'spp-platinum:',
        expectedProtectedURL: '/solutionpartners/drafts/automation/regression/protected-home',
      },
    },
    {
      tcid: '5',
      name: '@login-public-page-sign-in-with-non-member',
      testId: '@MWPW-140207',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/public-page',
      newsPath: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/partner-news',
      tags: '@dx-signin @regression @login @nopr',
      data: {
        partnerLevel: 'tpp-platinum:',
        expectedToSeeInURL: '/solutionpartners/error/contact-not-found',
      },
    },
    {
      tcid: '6',
      name: '@login-accessing-restricted-home-page-with-non-member-user-logged-in-to-adobe',
      testId: '@MWPW-140202',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/protected-home',
      baseURL: 'https://www.stage.adobe.com/partners.html',
      tags: '@dx-signin @regression @login @nopr',
      data: {
        partnerLevel: 'tpp-platinum:',
        expectedToSeeInURL: '/solutionpartners/error/contact-not-found',
      },
    },
    {
      tcid: '7',
      name: '@login-accessing-public-page-with-non-member-user-logged-in-to-adobe',
      testId: '@MWPW-140212',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/public-page',
      baseURL: 'https://www.stage.adobe.com/partners.html',
      tags: '@dx-signin @regression @login @nopr',
      data: {
        partnerLevel: 'tpp-platinum:',
        expectedToSeeInURL: '/solutionpartners/error/contact-not-found',
      },
    },
    {
      tcid: '8',
      name: '@login-accessing-restricted-home-page-with-non-logged-in-user',
      testId: '@MWPW-140213',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/protected-home',
      tags: '@dx-signin @regression @login @nopr',
      expectedToSeeInURL: 'https://auth-stg1.services.adobe.com/',
    },
    {
      tcid: '9',
      name: '@login-with-submitted-in-review-spp-user',
      testId: '@MWPW-140214',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/public-page',
      tags: '@dx-signin @regression @login @nopr',
      data: {
        partnerLevel: 'spp-submitted-in-review:',
        expectedLandingPageURL: 'https://partners.stage.adobe.com/solutionpartners/error/submitted-in-review',
      },
    },
    {
      tcid: '10',
      name: '@login-with-deactivated-spp-user',
      testId: '@MWPW-140224',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/public-page',
      tags: '@dx-signin @regression @login @nopr',
      data: {
        partnerLevel: 'spp-deactivated:',
        expectedLandingPageURL: 'https://partners.stage.adobe.com/solutionpartners/error/contact-inactive',
      },
    },
    {
      tcid: '11',
      name: '@login-with-expired-spp-user',
      testId: 'MWPW-140215',
      path: 'https://partners.stage.adobe.com/solutionpartners/drafts/automation/regression/public-page',
      tags: '@dx-signin @regression @login @nopr',
      data: {
        partnerLevel: 'spp-expired:',
        expectedLandingPageURL: 'https://partners.stage.adobe.com/solutionpartners/error/account-expired',
      },
    },
  ],
};
