module.exports = {
    name: 'Creative Cloud Page',
    features: [
        {
            tcid: '0',
            name: '@ArgentinaCCPageCheck',
            path: '/ar/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccArgentina',
        },
        {
            tcid: '1',
            name: '@BrazilCCPageCheck',
            path: '/br/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccBrazil',
        },
        {
            tcid: '2',
            name: '@CanadaEnglishCCPageCheck',
            path: '/ca/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccCanadaEnglish',
        },
        {
            tcid: '3',
            name: '@CanadaFrenchCCPageCheck',
            path: '/ca_fr/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccCanadaFrench',
        },
        {
            tcid: '4',
            name: '@ChileCCPageCheck',
            path: '/cl/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccChile',
        },
        {
            tcid: '5',
            name: '@ColombiaCCPageCheck',
            path: '/co/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccColombia',
        },
        {
            tcid: '6',
            name: '@CostaRicaCCPageCheck',
            path: '/cr/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccCostaRica',
        },
        {
            tcid: '7',
            name: '@EcuadorCCPageCheck',
            path: '/ec/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccEcuador',
        },
        {
            tcid: '8',
            name: '@GuatemalaCCPageCheck',
            path: '/gt/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccGuatemala',
        },
        {
            tcid: '9',
            name: '@LatinoAmericaCCPageCheck',
            path: '/la/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccLatinoAmerica',
        },
        {
            tcid: '10',
            name: '@MexicoCCPageCheck',
            path: '/mx/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccMexico',
        },
        {
            tcid: '11',
            name: '@PeruCCPageCheck',
            path: '/pe/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccperu',
        },
        {
            tcid: '12',
            name: '@PuertoRicoCCPageCheck',
            path: '/pr/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccPuertoRico',
        },
        {
            tcid: '13',
            name: '@UnitedStatesCCPageCheck',
            path: '/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccUnitedStates',
        },
        {
            tcid: '14',
            name: '@AfricaEnglishCCPageCheck',
            path: '/africa/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccAfricaEnglish',
        },
        {
            tcid: '15',
            name: '@BelgiumFrenchCCPageCheck',
            path: '/be_fr/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccBelgiumFrench',
        },
        {
            tcid: '16',
            name: '@BelgiumEnglishCCPageCheck',
            path: '/be_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccBelgiumEnglish',
        },
        {
            tcid: '17',
            name: '@BelgiumNederlandsCCPageCheck',
            path: '/be_nl/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccBelgiumNederlands',
        },
        {
            tcid: '18',
            name: '@CISEnglishCCPageCheck',
            path: '/cis_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccCISEnglish',
        },
        {
            tcid: '19',
            name: '@CISRussiaCCPageCheck',
            path: '/cis_ru/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccCISRussia',
        },
        {
            tcid: '20',
            name: '@DenmarkCCPageCheck',
            path: '/dk/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccDenmark',
        },
        {
            tcid: '21',
            name: '@DeutschlandCCPageCheck',
            path: '/de/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccDeutschland',
        },
        {
            tcid: '22',
            name: '@EestiCCPageCheck',
            path: '/ee/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccEesti',
        },
        {
            tcid: '23',
            name: '@EgytpEnglishCCPageCheck',
            path: '/eg_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccEgytpEnglish',
        },
        {
            tcid: '24',
            name: '@SpainCCPageCheck',
            path: '/es/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSpain',
        },
        {
            tcid: '25',
            name: '@FranceCCPageCheck',
            path: '/fr/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccFrance',
        },
        {
            tcid: '26',
            name: '@GreeceEnglishCCPageCheck',
            path: '/gr_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccGreeceEnglish',
        },
        {
            tcid: '27',
            name: '@GreeceCCPageCheck',
            path: '/gr_el/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccGreece',
        },
        {
            tcid: '28',
            name: '@IrelandCCPageCheck',
            path: '/ie/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccIreland',
        },
        {
            tcid: '29',
            name: '@IsraelEnglishCCPageCheck',
            path: '/il_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccIsraelEnglish',
        },
        {
            tcid: '30',
            name: '@ItalyCCPageCheck',
            path: '/it/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccItaly',
        },
        {
            tcid: '31',
            name: '@KuwaitEnglishCCPageCheck',
            path: '/kw_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccKuwaitEnglish',
        },
        {
            tcid: '32',
            name: '@LatviaCCPageCheck',
            path: '/lv/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccLatvia',
        },
        {
            tcid: '33',
            name: '@LithuaniaCCPageCheck',
            path: '/lt/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccLithuania',
        },
        {
            tcid: '34',
            name: '@LuxembourgGermanCCPageCheck',
            path: '/lu_de/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccLuxembourgGerman',
        },
        {
            tcid: '35',
            name: '@LuxembourgEnglishCCPageCheck',
            path: '/lu_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccLuxembourgEnglish',
        },
        {
            tcid: '36',
            name: '@LuxembourgFrenchCCPageCheck',
            path: '/lu_fr/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccLuxembourgFrench',
        },
        {
            tcid: '37',
            name: '@HungaryCCPageCheck',
            path: '/hu/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccHungary',
        },
        {
            tcid: '38',
            name: '@MiddleEastAndNorthAfricaEnglishCCPageCheck',
            path: '/mena_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccMiddleEastAndNorthAfricaEnglish',
        },
        {
            tcid: '39',
            name: '@NigeriaCCPageCheck',
            path: '/ng/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccNigeria',
        },
        {
            tcid: '40',
            name: '@NederlandCCPageCheck',
            path: '/nl/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccNederland',
        },
        {
            tcid: '41',
            name: '@NorwayCCPageCheck',
            path: '/no/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccNorway',
        },
        {
            tcid: '42',
            name: '@polandCCPageCheck',
            path: '/pl/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccPoland',
        },
        {
            tcid: '43',
            name: '@PortugalCCPageCheck',
            path: '/pt/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccPortugal',
        },
        {
            tcid: '44',
            name: '@QatarEnglishCCPageCheck',
            path: '/qa_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccQatarEnglish',
        },
        {
            tcid: '45',
            name: '@RomaniaCCPageCheck',
            path: '/ro/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccRomania',
        },
        {
            tcid: '46',
            name: '@SaudiArabiaEnglishCCPageCheck',
            path: '/sa_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSaudiArabiaEnglish',
        },
        {
            tcid: '47',
            name: '@SwitzerlandCCPageCheck',
            path: '/ch_de/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSwitzerland',
        },
        {
            tcid: '48',
            name: '@SloveniaCCPageCheck',
            path: '/si/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSlovenia',
        },
        {
            tcid: '49',
            name: '@SlovakiaCCPageCheck',
            path: '/sk/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSlovakia',
        },
        {
            tcid: '50',
            name: '@SouthAfricaCCPageCheck',
            path: '/za/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSouthAfrica',
        },
        {
            tcid: '51',
            name: '@SwitzerlandFrenchCCPageCheck',
            path: '/ch_fr/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSwitzerlandFrench',
        },
        {
            tcid: '52',
            name: '@FinlandCCPageCheck',
            path: '/fi/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccFinland',
        },
        {
            tcid: '53',
            name: '@SwedenCCPageCheck',
            path: '/se/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSweden',
        },
        {
            tcid: '54',
            name: '@SwitzerlandItalianCCPageCheck',
            path: '/ch_it/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSwitzerlandItalian',
        },
        {
            tcid: '55',
            name: '@TurkeyCCPageCheck',
            path: '/tr/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccTurkey',
        },
        {
            tcid: '56',
            name: '@UnitedArabEmiratesEnglishCCPageCheck',
            path: '/ae_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccUnitedArabEmiratesEnglish',
        },
        {
            tcid: '57',
            name: '@UnitedKingdomCCPageCheck',
            path: '/uk/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccUnitedKingdom',
        },
        {
            tcid: '58',
            name: '@AustriaCCPageCheck',
            path: '/at/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccAustria',
        },
        {
            tcid: '59',
            name: '@CzechRepublicCCPageCheck',
            path: '/cz/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccCzechRepublic',
        },
        {
            tcid: '60',
            name: '@BulgariaCCPageCheck',
            path: '/bg/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccBulgaria',
        },
        {
            tcid: '61',
            name: '@RussiaCCPageCheck',
            path: '/ru/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccRussia',
        },
        {
            tcid: '62',
            name: '@UkraineCCPageCheck',
            path: '/ua/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccUkraine',
        },
        {
            tcid: '63',
            name: '@IsraelCCPageCheck',
            path: '/il_he/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccIsrael',
        },
        {
            tcid: '64',
            name: '@UnitedArabEmiratesCCPageCheck',
            path: '/ae_ar/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccUnitedArabEmirates',
        },
        {
            tcid: '65',
            name: '@MiddleEastAndNorthAfricaCCPageCheck',
            path: '/mena_ar/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccMiddleEastAndNorthAfrica',
        },
        {
            tcid: '66',
            name: '@SaudiArabiaCCPageCheck',
            path: '/sa_ar/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSaudiArabia',
        },
        {
            tcid: '67',
            name: '@EgyptCCPageCheck',
            path: '/eg_ar/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccEgypt',
        },
        {
            tcid: '68',
            name: '@KuwaitCCPageCheck',
            path: '/kw_ar/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccKuwait',
        },
        {
            tcid: '69',
            name: '@QatarCCPageCheck',
            path: '/qa_ar/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccQatar',
        },
        {
            tcid: '70',
            name: '@AustraliaCCPageCheck',
            path: '/au/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccAustralia',
        },
        {
            tcid: '71',
            name: '@HongKongSAROfChinaCCPageCheck',
            path: '/hk_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccHongKongSAROfChina',
        },
        {
            tcid: '72',
            name: '@IndiaCCPageCheck',
            path: '/in/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccIndia',
        },
        {
            tcid: '73',
            name: '@IndonesiaCCPageCheck',
            path: '/id_id/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccIndonesia',
        },
        {
            tcid: '74',
            name: '@IndonesiaEnglishCCPageCheck',
            path: '/id_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccIndonesiaEnglish',
        },
        {
            tcid: '75',
            name: '@MalaysiaCCPageCheck',
            path: '/my_ms/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccMalaysia',
        },
        {
            tcid: '76',
            name: '@MalaysiaEnglishCCPageCheck',
            path: '/my_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccMalaysiaEnglish',
        },
        {
            tcid: '77',
            name: '@NewZelandCCPageCheck',
            path: '/nz/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccNewZeland',
        },
        {
            tcid: '78',
            name: '@PhilippinesEnglishCCPageCheck',
            path: '/ph_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccPhilippinesEnglish',
        },
        {
            tcid: '79',
            name: '@PhilippinesCCPageCheck',
            path: '/ph_fil/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccPhilippines',
        },
        {
            tcid: '80',
            name: '@SingaporeCCPageCheck',
            path: '/sg/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccSingapore',
        },
        {
            tcid: '81',
            name: '@ThailandEnglishCCPageCheck',
            path: '/th_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccThailand',
        },
        {
            tcid: '82',
            name: '@VietnamEnglishCCPageCheck',
            path: '/vn_en/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccvietnam',
        },
        {
            tcid: '83',
            name: '@VietnamCCPageCheck',
            path: '/vn_vi/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccVietnam',
        },
        {
            tcid: '84',
            name: '@IndiaHindiCCPageCheck',
            path: '/in_hi/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccIndiaHindi',
        },
        {
            tcid: '85',
            name: '@ThailandCCPageCheck',
            path: '/th_th/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccThailand',
        },
        {
            tcid: '86',
            name: '@ChinaCCPageCheck',
            path: '/cn/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccChina',
        },
        {
            tcid: '87',
            name: '@HongKongCCPageCheck',
            path: '/hk_zh/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccHongKong',
        },
        {
            tcid: '88',
            name: '@TaiwanCCPageCheck',
            path: '/tw/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccTaiwan',
        },
        {
            tcid: '89',
            name: '@JapanCCPageCheck',
            path: '/jp/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccJapan',
        },
        {
            tcid: '90',
            name: '@KoreaCCPageCheck',
            path: '/kr/creativecloud.html/?georouting=off',
            tags: '@ccpagesanity @ccKorea',
        },
    ]
}