module.exports = {
  name: 'AdobeHomePage',
  features: [
    {
      tcid: '0',
      name: '@ArgentinaHomePageGnavCheck',
      path: '/ar/?georouting=off',
      tags: '@gnavsanity @gnavhomeargentina',
      country: 'Argentina',
    },
    {
      tcid: '1',
      name: '@BrasilHomePageGnavCheck',
      path: '/br/?georouting=off',
      tags: '@gnavsanity @gnavhomebrasil',
      country: 'Brazil',
    },
    {
      tcid: '2',
      name: '@CanadaEnglishHomePageGnavCheck',
      path: '/ca/?georouting=off',
      tags: '@gnavsanity @gnavhomecanadaenglish',
      country: 'Canada English',
    },
    {
      tcid: '3',
      name: '@CanadaFrancaisHomePageGnavCheck',
      path: '/ca_fr/?georouting=off',
      tags: '@gnavsanity @gnavhomecanadafrancais',
      country: 'Canada French',
    },
    {
      tcid: '4',
      name: '@ChileHomePageGnavCheck',
      path: '/cl/?georouting=off',
      tags: '@gnavsanity @gnavhomechile',
      country: 'Chile',
    },
    {
      tcid: '5',
      name: '@ColombiaHomePageGnavCheck',
      path: '/co/?georouting=off',
      tags: '@gnavsanity @gnavhomecolombia',
      country: 'Colombia',
    },
    {
      tcid: '6',
      name: '@CostaRicaHomePageGnavCheck',
      path: '/cr/?georouting=off',
      tags: '@gnavsanity @gnavhomecostarica',
      country: 'Costa Rica',
    },
    {
      tcid: '7',
      name: '@EcuadorHomePageGnavCheck',
      path: '/ec/?georouting=off',
      tags: '@gnavsanity @gnavhomeecuador',
      country: 'Ecuador',
    },
    {
      tcid: '8',
      name: '@GuatemalaHomePageGnavCheck',
      path: '/gt/?georouting=off',
      tags: '@gnavsanity @gnavhomeguatemala',
      country: 'Guatemala',
    },
    {
      tcid: '9',
      name: '@Latin-AmericaHomePageGnavCheck',
      path: '/la/?georouting=off',
      tags: '@gnavsanity @gnavhomelatinamerica',
      country: 'Latin America',
    },
    {
      tcid: '10',
      name: '@MexicoHomePageGnavCheck',
      path: '/mx/?georouting=off',
      tags: '@gnavsanity @gnavhomemexico',
      country: 'Mexico',
    },
    {
      tcid: '11',
      name: '@PeruHomePageGnavCheck',
      path: '/pe/?georouting=off',
      tags: '@gnavsanity @gnavhomeperu',
      country: 'Peru',
    },
    {
      tcid: '12',
      name: '@Puerto-RicoHomePageGnavCheck',
      path: '/pr/?georouting=off',
      tags: '@gnavsanity @gnavhomepuertorico',
      country: 'Puerto Rico',
    },
    {
      tcid: '13',
      name: '@United-StatesHomePageGnavCheck',
      path: '/?georouting=off',
      tags: '@gnavsanity @gnavhomeunitedstates',
      country: 'United States',
    },
    {
      tcid: '14',
      name: '@Africa-EnglishHomePageGnavCheck',
      path: '/africa/?georouting=off',
      tags: '@gnavsanity @gnavhomeafricaenglish',
      country: 'Africa English',
    },
    {
      tcid: '15',
      name: '@Belgique-FrancaisHomePageGnavCheck',
      path: '/be_fr/?georouting=off',
      tags: '@gnavsanity @gnavhomebelgiquefrancais',
      country: 'Belgium French',
    },
    {
      tcid: '16',
      name: '@Belgium-EnglishHomePageGnavCheck',
      path: '/be_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeBelgiumEnglish',
      country: 'Belgium English',
    },
    {
      tcid: '17',
      name: '@Belgie-NederlandsHomePageGnavCheck',
      path: '/be_nl/?georouting=off',
      tags: '@gnavsanity @gnavhomeBelgieNederlands',
      country: 'Belgium Nederlands',
    },
    {
      tcid: '18',
      name: '@CIS–EnglishHomePageGnavCheck',
      path: '/cis_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeCISEnglish',
      country: 'CIS English',
    },
    {
      tcid: '19',
      name: '@CIS–RussianHomePageGnavCheck',
      path: '/cis_ru/?georouting=off',
      tags: '@gnavsanity @gnavhomeCISRussian',
      country: 'CIS Russian',
    },
    {
      tcid: '20',
      name: '@DanmarkHomePageGnavCheck',
      path: '/dk/?georouting=off',
      tags: '@gnavsanity @gnavhomeDanmark',
      country: 'Denmark',
    },
    {
      tcid: '21',
      name: '@DeutschlandHomePageGnavCheck',
      path: '/de/?georouting=off',
      tags: '@gnavsanity @gnavhomeDeutschland @germangnav',
      country: 'Germany',
    },
    {
      tcid: '22',
      name: '@EestiHomePageGnavCheck',
      path: '/ee/?georouting=off',
      tags: '@gnavsanity @gnavhomeEesti',
      country: 'Estonia',
    },
    {
      tcid: '23',
      name: '@Egypt-EnglishPageGnavCheck',
      path: '/eg_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeEgyptEnglish',
      country: 'Egypt English',
    },
    {
      tcid: '24',
      name: '@EspanaPageGnavCheck',
      path: '/es/?georouting=off',
      tags: '@gnavsanity @gnavhomeEspana',
      country: 'Spain',
    },
    {
      tcid: '25',
      name: '@FrancePageGnavCheck',
      path: '/fr/?georouting=off',
      tags: '@gnavsanity @gnavhomeFrance',
      country: 'France',
    },
    {
      tcid: '26',
      name: '@Greece-EnglishPageGnavCheck',
      path: '/gr_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeGreeceEnglish',
      country: 'Greece English',
    },
    {
      tcid: '27',
      name: '@GreecePageGnavCheck',
      path: '/gr_el/?georouting=off',
      tags: '@gnavsanity @gnavhomeGreece',
      country: 'Greece',
    },
    {
      tcid: '28',
      name: '@IrelandPageGnavCheck',
      path: '/ie/?georouting=off',
      tags: '@gnavsanity @gnavhomeIreland',
      country: 'Ireland',
    },
    {
      tcid: '29',
      name: '@Israel-EnglishPageGnavCheck',
      path: '/il_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeIsraelEnglish',
      country: 'Israel English',
    },
    {
      tcid: '30',
      name: '@ItaliaPageGnavCheck',
      path: '/it/?georouting=off',
      tags: '@gnavsanity @gnavhomeItalia',
      country: 'Italy',
    },
    {
      tcid: '31',
      name: '@Kuwait-EnglishPageGnavCheck',
      path: '/kw_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeKuwaitEnglish',
      country: 'Kuwait English',
    },
    {
      tcid: '32',
      name: '@LatvijaPageGnavCheck',
      path: '/lv/?georouting=off',
      tags: '@gnavsanity @gnavhomeLatvija',
      country: 'Latvia',
    },
    {
      tcid: '33',
      name: '@LietuvaPageGnavCheck',
      path: '/lt/?georouting=off',
      tags: '@gnavsanity @gnavhomeLietuva',
      country: 'Lithuania',
    },
    {
      tcid: '34',
      name: '@Luxembourg-DeutschPageGnavCheck',
      path: '/lu_de/?georouting=off',
      tags: '@gnavsanity @gnavhomeLuxembourg-Deutsch',
      country: 'Luxemburg German',
    },
    {
      tcid: '35',
      name: '@Luxembourg-EnglishPageGnavCheck',
      path: '/lu_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeLuxembourgEnglish',
      country: 'Luxemburg English',
    },
    {
      tcid: '36',
      name: '@Luxembourg-FrancaisPageGnavCheck',
      path: '/lu_fr/?georouting=off',
      tags: '@gnavsanity @gnavhomeLuxembourgFrancais',
      country: 'Luxemburg French',
    },
    {
      tcid: '37',
      name: '@HungaryPageGnavCheck',
      path: '/hu/?georouting=off',
      tags: '@gnavsanity @gnavhomeHungary',
      country: 'Hungary',
    },
    {
      tcid: '38',
      name: '@MiddleEastandNorthAfrica-EnglishPageGnavCheck',
      path: '/mena_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeMiddleEastandNorthAfricaEnglish',
      country: 'Middle East and North Africa English',
    },
    {
      tcid: '39',
      name: '@NigeriaPageGnavCheck',
      path: '/ng/?georouting=off',
      tags: '@gnavsanity @gnavhomeNigeria',
      country: 'Nigeria',
    },
    {
      tcid: '40',
      name: '@NederlandPageGnavCheck',
      path: '/nl/?georouting=off',
      tags: '@gnavsanity @gnavhomeNederland',
      country: 'Nederland',
    },
    {
      tcid: '41',
      name: '@NorwayPageGnavCheck',
      path: '/no/?georouting=off',
      tags: '@gnavsanity @gnavhomeNorway',
      country: 'Norway',
    },
    {
      tcid: '42',
      name: '@PolandPageGnavCheck',
      path: '/pl/?georouting=off',
      tags: '@gnavsanity @gnavhomePoland',
      country: 'Poland',
    },
    {
      tcid: '43',
      name: '@PortugalPageGnavCheck',
      path: '/pt/?georouting=off',
      tags: '@gnavsanity @gnavhomePortugal',
      country: 'Portugal',
    },
    {
      tcid: '44',
      name: '@Qatar-EnglishPageGnavCheck',
      path: '/qa_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeQatarEnglish',
      country: 'Qatar English',
    },
    {
      tcid: '45',
      name: '@RomaniaPageGnavCheck',
      path: '/ro/?georouting=off',
      tags: '@gnavsanity @gnavhomeRomania',
      country: 'Romania',
    },
    {
      tcid: '46',
      name: '@SaudiArabia-EnglishPageGnavCheck',
      path: '/sa_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeSaudiArabiaEnglish',
      country: 'Saudi Arabia',
    },
    {
      tcid: '47',
      name: '@SchweizPageGnavCheck',
      path: '/ch_de/?georouting=off',
      tags: '@gnavsanity @gnavhomeSchweiz',
      country: 'Switzerland',
    },
    {
      tcid: '48',
      name: '@SlovenijaPageGnavCheck',
      path: '/si/?georouting=off',
      tags: '@gnavsanity @gnavhomeSlovenija',
      country: 'Slovenia',
    },
    {
      tcid: '49',
      name: '@SlovenskoPageGnavCheck',
      path: '/sk/?georouting=off',
      tags: '@gnavsanity @gnavhomeSlovensko',
      country: 'Slovakia',
    },
    {
      tcid: '50',
      name: '@SouthAfricaPageGnavCheck',
      path: '/za/?georouting=off',
      tags: '@gnavsanity @gnavhomeSouthAfrica',
      country: 'South Africa',
    },
    {
      tcid: '51',
      name: '@SwitzerlandPageGnavCheck',
      path: '/ch_fr/?georouting=off',
      tags: '@gnavsanity @gnavhomeSwitzerland',
      country: 'Switzerland French',
    },
    {
      tcid: '52',
      name: '@FinlandPageGnavCheck',
      path: '/fi/?georouting=off',
      tags: '@gnavsanity @gnavhomeFinland',
      country: 'Finland',
    },
    {
      tcid: '53',
      name: '@SverigePageGnavCheck',
      path: '/se/?georouting=off',
      tags: '@gnavsanity @gnavhomeSverige',
      country: 'Sweden',
    },
    {
      tcid: '54',
      name: '@SvizzeraPageGnavCheck',
      path: '/ch_it/?georouting=off',
      tags: '@gnavsanity @gnavhomeSvizzera',
      country: 'Switzerland Italian',
    },
    {
      tcid: '55',
      name: '@TurkeyPageGnavCheck',
      path: '/tr/?georouting=off',
      tags: '@gnavsanity @gnavhomeTurkey',
      country: 'Turkey',
    },
    {
      tcid: '56',
      name: '@UnitedArabEmirates-EnglishPageGnavCheck',
      path: '/ae_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeUnitedArabEmiratesEnglish',
      country: 'United Arab Emirates English',
    },
    {
      tcid: '57',
      name: '@UnitedKingdomPageGnavCheck',
      path: '/uk/?georouting=off',
      tags: '@gnavsanity @gnavhomeUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '58',
      name: '@austriaPageGnavCheck',
      path: '/at/?georouting=off',
      tags: '@gnavsanity @gnavhomeaustria',
      country: 'Austria',
    },
    {
      tcid: '59',
      name: '@CzechRepublicPageGnavCheck',
      path: '/cz/?georouting=off',
      tags: '@gnavsanity @gnavhomeCzechRepublic',
      country: 'Czech Republic',
    },
    {
      tcid: '60',
      name: '@BulgariaPageGnavCheck',
      path: '/bg/?georouting=off',
      tags: '@gnavsanity @gnavhomeBulgaria',
      country: 'Bulgaria',
    },
    {
      tcid: '61',
      name: '@RussiaPageGnavCheck',
      path: '/ru/?georouting=off',
      tags: '@gnavsanity @gnavhomeRussia',
      country: 'Russia',
    },
    {
      tcid: '62',
      name: '@UkrainePageGnavCheck',
      path: '/ua/?georouting=off',
      tags: '@gnavsanity @gnavhomeUkraine',
      country: 'Ukraine',
    },
    {
      tcid: '63',
      name: '@IsraelHebrewPageGnavCheck',
      path: '/il_he/?georouting=off',
      tags: '@gnavsanity @gnavhomeIsraelHebrew',
      country: 'Israel Hebrew',
    },
    {
      tcid: '64',
      name: '@UAEPageGnavCheck',
      path: '/ae_ar/?georouting=off',
      tags: '@gnavsanity @gnavhomeUAE',
      country: 'UAE',
    },
    {
      tcid: '65',
      name: '@MiddleEastAndNorthAfricaPageGnavCheck',
      path: '/mena_ar/?georouting=off',
      tags: '@gnavsanity @gnavhomeMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '66',
      name: '@KingdomOfSaudiArabiaPageGnavCheck',
      path: '/sa_ar/?georouting=off',
      tags: '@gnavsanity @gnavhomeSaudiArabia',
      country: 'Kingdom Of Saudi Arabia',
    },
    {
      tcid: '67',
      name: '@EgyptPageGnavPageCheck',
      path: '/eg_ar/?georouting=off',
      tags: '@gnavsanity @gnavhomeEgypt',
      country: 'Egypt',
    },
    {
      tcid: '68',
      name: '@KuwaitPageGnavCheck',
      path: '/kw_ar/?georouting=off',
      tags: '@gnavsanity @gnavhomeKuwait',
      country: 'Kuwait',
    },
    {
      tcid: '69',
      name: '@QatarPageGnavCheck',
      path: '/qa_ar/?georouting=off',
      tags: '@gnavsanity @gnavhomeQatar',
      country: 'Qatar',
    },
    {
      tcid: '70',
      name: '@AustraliaPageGnavCheck',
      path: '/au/?georouting=off',
      tags: '@gnavsanity @gnavhomeAustralia',
      country: 'Australia',
    },
    {
      tcid: '71',
      name: '@HongKongChinaPageGnavCheck',
      path: '/hk_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeHongKongChina',
      country: 'Hong Kong China',
    },
    {
      tcid: '72',
      name: '@IndiaPageGnavCheck',
      path: '/in/?georouting=off',
      tags: '@gnavsanity @gnavhomeIndia',
      country: 'India',
    },
    {
      tcid: '73',
      name: '@IndonesiaPageGnavCheck',
      path: '/id_id/?georouting=off',
      tags: '@gnavsanity @gnavhomeIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '74',
      name: '@Indonesia-EnglishPageGnavCheck',
      path: '/id_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '75',
      name: '@MalaysiaPageGnavCheck',
      path: '/my_ms/?georouting=off',
      tags: '@gnavsanity @gnavhomeMalaysia',
      country: 'Malaysia',
    },
    {
      tcid: '76',
      name: '@Malaysia-EnglishPageGnavCheck',
      path: '/my_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeMalaysiaEnglish',
      country: 'Malaysia English',
    },
    {
      tcid: '77',
      name: '@NewZealandPageGnavCheck',
      path: '/nz/?georouting=off',
      tags: '@gnavsanity @gnavhomeNewZealand',
      country: 'New Zealand',
    },
    {
      tcid: '78',
      name: '@Philippines-EnglishPageGnavCheck',
      path: '/ph_en/?georouting=off',
      tags: '@gnavsanity @gnavhomePhilippinesEnglish',
      country: 'Philippines English',
    },
    {
      tcid: '79',
      name: '@PhilippinesPageGnavCheck',
      path: '/ph_fil/?georouting=off',
      tags: '@gnavsanity @gnavhomePhilippines',
      country: 'Philippines',
    },
    {
      tcid: '80',
      name: '@SingaporePageGnavCheck',
      path: '/sg/?georouting=off',
      tags: '@gnavsanity @gnavhomeSingapore',
      country: 'Singapore',
    },
    {
      tcid: '81',
      name: '@Thailand-EnglishPageGnavCheck',
      path: '/th_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '82',
      name: '@Vietnam-EnglishPageGnavCheck',
      path: '/vn_en/?georouting=off',
      tags: '@gnavsanity @gnavhomeVietnamEnglish',
      country: 'Vietnam English',
    },
    {
      tcid: '83',
      name: '@VietnamPageGnavCheck',
      path: '/vn_vi/?georouting=off',
      tags: '@gnavsanity @gnavhomeVietnam',
      country: 'Vietnam',
    },
    {
      tcid: '84',
      name: '@India-HindiPageGnavCheck',
      path: '/in_hi/?georouting=off',
      tags: '@gnavsanity @gnavhomeIndiaHindi',
      country: 'India Hindi',
    },
    {
      tcid: '85',
      name: '@ThailandPageGnavCheck',
      path: '/th_th/?georouting=off',
      tags: '@gnavsanity @gnavhomeThailand',
      country: 'Thailand',
    },
    {
      tcid: '86',
      name: '@ChinaPageGnavCheck',
      path: '/cn/?georouting=off',
      tags: '@gnavsanity @gnavhomeChina',
      country: 'China',
    },
    {
      tcid: '87',
      name: '@HongKongPageGnavCheck',
      path: '/hk_zh/?georouting=off',
      tags: '@gnavsanity @gnavhomeHongKong',
      country: 'Hong Kong',
    },
    {
      tcid: '88',
      name: '@TaiwanPageGnavCheck',
      path: '/tw/?georouting=off',
      tags: '@gnavsanity @gnavhomeTaiwan',
      country: 'Taiwan',
    },
    {
      tcid: '89',
      name: '@JapanPageGnavCheck',
      path: '/jp/?georouting=off',
      tags: '@gnavsanity @gnavhomeJapan',
      country: 'Japan',
    },
    {
      tcid: '90',
      name: '@KoreaPageGnavCheck',
      path: '/kr/?georouting=off#modal-hash',
      tags: '@gnavsanity @gnavhomeKorea',
      country: 'Korea',
    },
  ],
};
