module.exports = {

  features: [
    {
      tcid: '0',
      name: '@USPhotoshopPageGnavCheck',
      path: '/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopUS',
      country: 'US',
    },
    {
      tcid: '1',
      name: '@GermanyPhotoshopPageCheck',
      path: '/de/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopGermany',
      country: 'Germany',
    },
    {
      tcid: '2',
      name: '@FrancePhotoshopPageCheck',
      path: '/fr/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopFrance',
      country: 'France',
    },
    {
      tcid: '3',
      name: '@ItalyPhotoshopPageCheck',
      path: '/it/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopItaly',
      country: 'Italy',
    },
    {
      tcid: '4',
      name: '@UnitedKingdomPhotoshopPageCheck',
      path: '/uk/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopUnitedKingdom',
      country: 'United Kingdom',
    },
    {
      tcid: '5',
      name: '@MiddleEastAndNorthAfricaPhotoshopPageCheck',
      path: '/mena_ar/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopMiddleEastAndNorthAfrica',
      country: 'Middle East And North Africa',
    },
    {
      tcid: '6',
      name: '@JapanPhotoshopPageCheck',
      path: '/jp/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopJapan',
      country: 'Japan',
    },
    {
      tcid: '7',
      name: '@IndiaPhotoshopPageCheck',
      path: '/in/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopIndia',
      country: 'India',
    },
    {
      tcid: '8',
      name: '@SpainPhotoshopPageCheck',
      path: '/es/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopSpain',
      country: 'Spain',
    },
    {
      tcid: '9',
      name: '@CanadaEnglishPhotoshopPageCheck',
      path: '/ca/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopCanadaEnglish',
      country: 'Canada English',
    },
    {
      tcid: '10',
      name: '@KoreaPhotoshopPageCheck',
      path: '/kr/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopKorea',
      country: 'Korea',
    },
    {
      tcid: '11',
      name: '@CanadaFrenchPhotoshopPageCheck',
      path: '/ca_fr/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopCanadaFrench',
      country: 'Canada French',
    },
    {
      tcid: '12',
      name: '@PolandPhotoshopPageCheck',
      path: '/pl/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopPoland',
      country: 'Poland',
    },
    {
      tcid: '13',
      name: '@MexicoPhotoshopPageCheck',
      path: '/mx/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopMexico',
      country: 'Mexico',
    },
    {
      tcid: '14',
      name: '@AustraliaPhotoshopPageCheck',
      path: '/au/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopAustralia',
      country: 'Australia',
    },
    {
      tcid: '15',
      name: '@IndonesiaPhotoshopPageCheck',
      path: '/id_id/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopIndonesia',
      country: 'Indonesia',
    },
    {
      tcid: '16',
      name: '@IndonesiaEnglishPhotoshopPageCheck',
      path: '/id_en/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopIndonesiaEnglish',
      country: 'Indonesia English',
    },
    {
      tcid: '17',
      name: '@TurkeyPhotoshopPageCheck',
      path: '/tr/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopTurkey',
      country: 'Turkey',
    },
    {
      tcid: '18',
      name: '@ThailandEnglishPhotoshopPageCheck',
      path: '/th_en/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopThailandEnglish',
      country: 'Thailand English',
    },
    {
      tcid: '19',
      name: '@ThailandphotoshopPageCheck',
      path: '/th_th/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopThailand',
      country: 'Thailand',
    },
    {
      tcid: '20',
      name: '@SingaporePhotoshopPageCheck',
      path: '/sg/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopSingapore',
      country: 'Singapore',
    },
    {
      tcid: '21',
      name: '@PhilippinePhotoshopPageCheck',
      path: '/ph_fil/products/photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshopPageSanity @PhotoshopPhilippines',
      country: 'Philippines',
    },
    {
      tcid: '22',
      name: '@PhilippineEnglishPhotoshopPageCheck',
      path: '/ph_en/products/Photoshop.html?georouting=off#modal-hash',
      tags: '@PhotoshoPageSanity @PhotoshopPhilippinesEnglish',
      country: 'Philippines English',
    },
  ],
};
