module.exports = {
  FeatureName: 'Blog URL Redirects',
  features: [
    {
      tcid: '0',
      name: '@Topic URL Redirects',
      path: {
        '/topics/stock.html': '/en/topics/stock',
        '/tag/coronavirus/': '/en/topics/covid-19',
        '/tag/inside-adobe/': '/en/topics/adobe-culture',
        '/tag/xd-updates/': '/en/topics/xd',
        '/acrolaw/': '/en/topics/acrobat',
        '/lightroomjournal/': '/en/topics/lightroom',
        '/creativity/': '/en/topics/creativity',
        '/adobemax/': '/en/topics/adobe-max',
        '/news/': '/en/topics/news',
        '/creativity/design/': '/en/topics/creativity',
        '/customer-experience/advertising/': '/en/topics/advertising',
        '/customer-experience/': '/en/topics/digital-transformation',
        '/customer-experience/analytics/': '/en/topics/digital-transformation',
        '/en/publish/2018/12/05/the-style-spotlight-greg-noire': '/en/topics/photography',
        '/de/topics/data--privacy': '/de/topics/data-privacy',
        '/es/topics/data--privacy': '/es/topics/data-privacy',
        '/fr/topics/data--privacy': '/fr/topics/data-privacy',
        '/br/topics/data--privacy': '/br/topics/data-privacy',
        '/ko/topics/data--privacy': '/ko/topics/data-privacy',
        '/jp/topics/data--privacy': '/jp/topics/data-privacy',
        '/de/topics/trends--research': '/de/topics/trends-research',
        '/es/topics/trends--research': '/es/topics/trends-research',
        '/fr/topics/trends--research': '/fr/topics/trends-research',
        '/br/topics/trends--research': '/br/topics/trends-research',
        '/ko/topics/trends--research': '/ko/topics/trends-research',
        '/jp/topics/trends--research': '/jp/topics/trends-research',
      },
      tags: '@topic-url-redirect @smoke @regression @blog',
    },
    {
      tcid: '1',
      name: '@Index URL Redirects',
      path: {
        '/japan/experiencecloud/': '/jp/',
        '/creativestation/': '/jp/',
        '/japan-conversations/': '/jp/',
        '/documentcloudjapan/': '/jp/',
        '/latinoamerica/  ': '/es/',
        '/brasil/': '/br/',
        '/it': '/it/',
        '/creative/': '/en/uk',
        '/digitaleurope/': '/en/uk',
        '/en/uk.html': '/en/uk',
        '/en/topics/uk-exclusive': '/en/uk',
        '/creativedialogue/': '/ko/',   
      },
      tags: '@index-url-redirect @smoke @regression @blog',
    },
    {
      tcid: '2',
      name: '@Author URL Redirects',
      path: {
        '/author/theresa-rostek/  ': '/en/authors/theresa-rostek',
        '/author/valentina-arismendi/': '/en/authors/valentina-arismendi',
        '/author/minson-chen/': '/en/authors/minson-chen',
        '/author/irene-malatesta/': '/en/authors/irene-malatesta',
        '/author/david-parmenter/': '/en/authors/david-parmenter',
        '/author/jperera/': '/en/authors/jon-perera',
      },
      tags: '@author-url-redirect @smoke @regression @blog',
    },
    {
      tcid: '3',
      name: '@Publish URL Redirects',
      path: {
        '/en/publish/2018/12/05/the-style-spotlight-greg-noire': '/en/topics/photography',
        '/en/publish/2018/11/14/the-style-spotlight-sam-horine': '/en/topics/photography',
        '/en/publish/2018/10/12/the-style-spotlight-elise-sterck': '/en/topics/photoshop',
        '/en/publish/2018/10/12/the-style-spotlight-elise-sterck': '/en/topics/photoshop',
        '/en/publish/2020/11/09/adobe-to-acquire-workfront': '/en/2020/12/07/adobe-completes-workfront-acquisition',
      },
      tags: '@author-url-redirect @smoke @regression @blog',
    },
  ],
};
