module.exports = {
  name: 'Caas Visual Comparison',
  features: [
    {
      tcid: '0',
      name: '@caas-visual-onehalfcollection-desktop',
      stable: '/fragments/caas/test-pages/onehalfcollection',
      beta: '/fragments/caas/test-pages/onehalfcollection?caasver=beta',
      tags: '@caas-visual-onehalfcollection-desktop, @caas-visual-desktop, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '1',
      name: '@caas-visual-threefourthscollection-desktop',
      stable: '/fragments/caas/test-pages/threefourthscollection',
      beta: '/fragments/caas/test-pages/threefourthscollection?caasver=beta',
      tags: '@caas-visual-threefourthscollection-desktop, @caas-visual-desktop, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '2',
      name: '@caas-visual-halfheightcollection-desktop',
      stable: '/fragments/caas/test-pages/halfheightcollection',
      beta: '/fragments/caas/test-pages/halfheightcollection?caasver=beta',
      tags: '@caas-visual-halfheightcollection-desktop, @caas-visual-desktop, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '3',
      name: '@caas-visual-fullwidthcollection-desktop',
      stable: '/fragments/caas/test-pages/textcardcollection',
      beta: '/fragments/caas/test-pages/textcardcollection?caasver=beta',
      tags: '@caas-visual-fullwidthcollection-desktop, @caas-visual-desktop, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '4',
      name: '@caas-visual-onehalfcollection-tablet',
      stable: '/fragments/caas/test-pages/onehalfcollection',
      beta: '/fragments/caas/test-pages/onehalfcollection?caasver=beta',
      tags: '@caas-visual-onehalfcollection-tablet, @caas-visual-tablet, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '5',
      name: '@caas-visual-threefourthscollection-tablet',
      stable: '/fragments/caas/test-pages/threefourthscollection',
      beta: '/fragments/caas/test-pages/threefourthscollection?caasver=beta',
      tags: '@caas-visual-threefourthscollection-tablet, @caas-visual-tablet, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '6',
      name: '@caas-visual-halfheightcollection-tablet',
      stable: '/fragments/caas/test-pages/halfheightcollection',
      beta: '/fragments/caas/test-pages/halfheightcollection?caasver=beta',
      tags: '@caas-visual-halfheightcollection-tablet, @caas-visual-tablet, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '7',
      name: '@caas-visual-fullwidthcollection-tablet',
      stable: '/fragments/caas/test-pages/textcardcollection',
      beta: '/fragments/caas/test-pages/textcardcollection?caasver=beta',
      tags: '@caas-visual-fullwidthcollection-tablet, @caas-visual-tablet, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '8',
      name: '@caas-visual-onehalfcollection-phone',
      stable: '/fragments/caas/test-pages/onehalfcollection',
      beta: '/fragments/caas/test-pages/onehalfcollection?caasver=beta',
      tags: '@caas-visual-onehalfcollection-phone, @caas-visual-phone, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '9',
      name: '@caas-visual-threefourthscollection-phone',
      stable: '/fragments/caas/test-pages/threefourthscollection',
      beta: '/fragments/caas/test-pages/threefourthscollection?caasver=beta',
      tags: '@caas-visual-threefourthscollection-phone, @caas-visual-phone, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '10',
      name: '@caas-visual-halfheightcollection-phone',
      stable: '/fragments/caas/test-pages/halfheightcollection',
      beta: '/fragments/caas/test-pages/halfheightcollection?caasver=beta',
      tags: '@caas-visual-halfheightcollection-phone, @caas-visual-phone, @visual, @visual-smoke, @visual-regression',
    },
    {
      tcid: '11',
      name: '@caas-visual-fullwidthcollection-phone',
      stable: '/fragments/caas/test-pages/textcardcollection',
      beta: '/fragments/caas/test-pages/textcardcollection?caasver=beta',
      tags: '@caas-visual-fullwidthcollection-phone, @caas-visual-phone, @visual, @visual-smoke, @visual-regression',
    },
  ],
};
