module.exports = {
  name: 'Quiz Recommender Blocks',
  features: [
    {
      tcid: '0',
      name: '@uar-quiz-ai-acrobatpro',
      tags: '@uar-quiz-ai-acrobatpro @uar-quiz-ai',
      data: 'data/uar/quiz/ai/acrobatpro.yml',
    },
    {
      tcid: '1',
      name: '@uar-quiz-ai-aftereffects',
      tags: '@uar-quiz-ai-aftereffects @uar-quiz-ai',
      data: 'data/uar/quiz/ai/aftereffects.yml',
    },
    {
      tcid: '2',
      name: '@uar-quiz-ai-animate',
      tags: '@uar-quiz-ai-animate @uar-quiz-ai',
      data: 'data/uar/quiz/ai/animate.yml',
    },
    {
      tcid: '3',
      name: '@uar-quiz-ai-audition',
      tags: '@uar-quiz-ai-audition @uar-quiz-ai',
      data: 'data/uar/quiz/ai/audition.yml',
    },
    {
      tcid: '4',
      name: '@uar-quiz-ai-designer',
      tags: '@uar-quiz-ai-designer @uar-quiz-ai',
      data: 'data/uar/quiz/ai/designer.yml',
    },
    {
      tcid: '5',
      name: '@uar-quiz-ai-express',
      tags: '@uar-quiz-ai-express @uar-quiz-ai',
      data: 'data/uar/quiz/ai/express.yml',
    },
    {
      tcid: '6',
      name: '@uar-quiz-ai-illustrator',
      tags: '@uar-quiz-ai-illustrator @uar-quiz-ai',
      data: 'data/uar/quiz/ai/illustrator.yml',
    },
    {
      tcid: '7',
      name: '@uar-quiz-ai-indesign',
      tags: '@uar-quiz-ai-indesign @uar-quiz-ai',
      data: 'data/uar/quiz/ai/indesign.yml',
    },
    {
      tcid: '8',
      name: '@uar-quiz-ai-lightroom',
      tags: '@uar-quiz-ai-lightroom @uar-quiz-ai',
      data: 'data/uar/quiz/ai/lightroom.yml',
    },
    {
      tcid: '9',
      name: '@uar-quiz-ai-modeler',
      tags: '@uar-quiz-ai-modeler @uar-quiz-ai',
      data: 'data/uar/quiz/ai/modeler.yml',
    },
    {
      tcid: '10',
      name: '@uar-quiz-ai-painter',
      tags: '@uar-quiz-ai-painter @uar-quiz-ai',
      data: 'data/uar/quiz/ai/painter.yml',
    },
    {
      tcid: '11',
      name: '@uar-quiz-ai-photoshop',
      tags: '@uar-quiz-ai-photoshop @uar-quiz-ai',
      data: 'data/uar/quiz/ai/photoshop.yml',
    },
    {
      tcid: '12',
      name: '@uar-quiz-ai-premierepro',
      tags: '@uar-quiz-ai-premierepro @uar-quiz-ai',
      data: 'data/uar/quiz/ai/premierepro.yml',
    },
    {
      tcid: '13',
      name: '@uar-quiz-ai-sampler',
      tags: '@uar-quiz-ai-sampler @uar-quiz-ai',
      data: 'data/uar/quiz/ai/sampler.yml',
    },
    {
      tcid: '14',
      name: '@uar-quiz-ai-stager',
      tags: '@uar-quiz-ai-stager @uar-quiz-ai',
      data: 'data/uar/quiz/ai/stager.yml',
    },
  ],
};
