module.exports = {
  name: 'Quiz Recommender Blocks',
  features: [
    {
      tcid: '0',
      name: '@quiz single template',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@uar-quiz-single-template @uar-quiz-static',
      data: 'data/uar/quiz/quiz-single-template.yml',
    },
    {
      tcid: '1',
      name: '@quiz double template',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@uar-quiz-double-template @uar-quiz-static',
      data: 'data/uar/quiz/quiz-double-template.yml',
    },
    {
      tcid: '2',
      name: '@quiz triple template',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@uar-quiz-triple-template @uar-quiz-static',
      data: 'data/uar/quiz/quiz-triple-template.yml',
    },
    {
      tcid: '3',
      name: '@quiz single flagship photo',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@uar-quiz-single-flagship-photo @uar-quiz-static',
      data: 'data/uar/quiz/quiz-single-flagship-photo.yml',
    },
    {
      tcid: '4',
      name: '@quiz single flagship video',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@uar-quiz-single-flagship-video @uar-quiz-static',
      data: 'data/uar/quiz/quiz-single-flagship-video.yml',
    },
    {
      tcid: '5',
      name: '@quiz double flagship design illustration',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@uar-quiz-double-flagship-design-illustration @uar-quiz-static',
      data: 'data/uar/quiz/quiz-double-flagship-design-illustration.yml',
    },
    {
      tcid: '6',
      name: '@quiz double flagship photo illustration',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@uar-quiz-double-flagship-photo-illustration @uar-quiz-static',
      data: 'data/uar/quiz/quiz-double-flagship-photo-illustration.yml',
    },
    {
      tcid: '7',
      name: '@quiz triple flagship photo video pdf',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@uar-quiz-triple-flagship-photo-video-pdf @uar-quiz-static',
      data: 'data/uar/quiz/quiz-triple-flagship-photo-video-pdf.yml',
    },
    {
      tcid: '8',
      name: '@quiz single 3D',
      path: '/creativecloud/quiz-recommender.html',
      tags: '@uar-quiz-single-3D @uar-quiz-static',
      data: 'data/uar/quiz/quiz-single-3D.yml',
    },
  ],
};
