module.exports = {
  '@milo_live': 'https://main--milo--adobecom.hlx.live',
  '@milo_prod': 'https://milo.adobe.com',
  '@feds_live': 'https://gnav--milo--adobecom.hlx.live',
  '@bacom_live': 'https://main--bacom--adobecom.hlx.live',
  '@bacomblog_live': 'https://main--business-website--adobe.hlx.live',
  '@stock_live': 'https://main--stock--adobecom.hlx.live',
  '@adobestock_live': 'https://main--adobestock--adobecom.hlx.live',
  '@dc_live': 'https://main--dc--adobecom.hlx.live',
  '@adobe_stage': 'https://www.stage.adobe.com',
  '@adobe_prod': 'https://www.adobe.com',
  '@bacom_prod': 'https://business.adobe.com',
  '@bacom_stage': 'https://business.stage.adobe.com',
  '@blog_prod': 'https://blog.adobe.com',
  '@milo_blog_live': 'https://main--blog--adobecom.hlx.live',
  '@cc_live': 'https://main--cc--adobecom.hlx.live',
  '@uar_live': 'https://uar-integration--milo--adobecom.hlx.live',
  '@local3000': 'http://localhost:3000',
  '@local6456': 'http://localhost:6456',
  '@helpxInternal_live':'https://helpx-internal.stage.adobe.com',
};
