module.exports = {
  '@milo': 'https://main--milo--adobecom.hlx.live',
  '@milo_prod': 'https://milo.adobe.com/',
  '@bacom': 'https://main--bacom--adobecom.hlx.live',
  '@bacomblog': 'https://main--business-website--adobe.hlx.live',
  '@stock': 'https://main--stock--adobecom.hlx.live',
  '@dc_preview': 'https://main--dc--adobecom.hlx.page',
  '@dc_live': 'https://main--dc--adobecom.hlx.live',
  '@adobe_stage': 'https://www.stage.adobe.com',
  '@adobe_prod': 'https://www.adobe.com',
  '@bacom_prod': 'https://business.adobe.com',
  '@blog': 'https://main--blog--adobe.hlx.live',
  '@local3000': 'http://localhost:3000',
  '@local6456': 'http://localhost:6456',
};
