module.exports = {
  name: 'CodeBlock',
  features: [
    {
      tcid: '0',
      name: '@codeBlock',
      path: '/automation/blocks/code-block',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '1',
      name: '@codeBlockwihtoutspecifyinglanguage',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '2',
      name: '@codeBlockAS3withSmallLetters',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '3',
      name: '@codeBlockAS3withcapitalLetters',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '4',
      name: '@codeBlockAS3withcapitalLetterswithlinenumbers',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '5',
      name: '@codeBlockColdFusion',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '6',
      name: '@codeBlockCplusPlus',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '7',
      name: '@codeBlockCSS',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '8',
      name: '@codeBlockJava',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '9',
      name: '@codeBlockJava',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '10',
      name: '@codeBlockPHP',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '11',
      name: '@codeBlockSQL',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '12',
      name: '@codeBlockMXML',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '13',
      name: '@codeBlockXML',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '14',
      name: '@codeBlockShell',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '15',
      name: '@codeBlockPlain',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '16',
      name: '@codeBlockAS3WithLineNumber',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '17',
      name: '@codeBlockColdFusionWithLineNumber',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '18',
      name: '@codeBlockCSSWithLineNumber',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '19',
      name: '@codeBlockJAVAWithLineNumber',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '20',
      name: '@codeBlockjavascriptWithLineNumber',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '21',
      name: '@codeBlockPHPWithLineNumber',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
    {
      tcid: '22',
      name: '@codeBlockSQLWithLineNumber',
      path: '/automation/blocks/Code_Block/code-block.html',
      tags: '@codeBlk @regression @helpx',
    },
  ],
};
