module.exports = {
  name: 'Redirects',
  features: [
    {
      tcid: '0',
      name: 'Bacom redirects for URLs without trailing slashes',
      path: [
        '/',
        '/au',
        '/uk',
        '/de',
        '/fr',
        '/jp',
        '/blog',
        '/au/blog',
        '/uk/blog',
        '/de/blog',
        '/fr/blog',
        '/jp/blog',
        '/kr/blog',
      ],
      tags: '@redirects @bacom @bacomSmoke @regression',
    },
    {
      tcid: '1',
      name: 'Checking URLs that should get .html appended',
      path: [
        '/customer-success-stories/',
        '/customer-success-stories',
        '/resources/',
        '/resources/main',
        '/request-consultation/experience-cloud/',
        '/products/genstudio',
        '/products/experience-manager/sites/aem-sites',
        '/products/real-time-customer-data-platform/rtcdp',
        '/resources/holiday-shopping-report',
        '/products/pricing',
        '/products/marketo/marketo-measure',
        '/au/products/real-time-customer-data-platform/rtcdp',
        '/uk/resources/real-time-cdp',
        '/de/request-consultation/experience-cloud',
        '/fr/resources/',
        '/jp/request-consultation/experience-cloud',
      ],
      tags: '@redirects @bacom @bacomSmoke @regression',
    },
  ],
};
