name: Run Nala Daily Visual Comparison

on:
  schedule:
    - cron: "0 19 * * *"

jobs:
  platform_matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Running tests
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out nala repository
        uses: actions/checkout@v3
      - name: Check out nala screenshots repository
        uses: actions/checkout@v3
        with:
          repository: adobecom/nala-screenshots
          ref: main
      - name: Copy base screenshots to test screenshot path
        working-directory: ${{ github.workspace }}/nala
        run: ./runVisualPrep.sh
      - name: Run Nala Visual Comparison ${{ matrix.os }}
        working-directory: ${{ github.workspace }}/nala
        run: ./
        env:
          isVisual: true
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
      - name: Persist JSON Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nala-results
          path: nala-results.json
          retention-days: 30
      - name: Persist Screenshots Artifact
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: vc-screenshots-failures
          path: test-results/
          retention-days: 30
