name: Run Nala Debugging

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags, if empty all tests will run. i.e., @marquee'
        required: false
        type: string
      platform:
        description: 'Platform to run tests on; select one, options: [ubuntu-latest, windows-latest, macos-latest]'
        required: true
        type: string

jobs:
  action:
    name: Debugging tests
    runs-on: ${{ inputs.platform }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run Nala for Trace Viewer ${{ inputs.platform }}
        uses: ./
        env:
          labels: ${{ inputs.tags }}
          reporter: html
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
      - name: Nala Reporting
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
