name: Run Nala Manually

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags, if empty all tests will run. i.e., @marquee'
        required: false
        type: string

jobs:
  action:
    name: Running tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run Nala
        uses: ./
        env:
          labels: ${{ inputs.tags }}
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
      - name: Persist JSON Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nala-results
          path: nala-results.json
          retention-days: 30
