name: Run Nala

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  action:
    name: Running tests
    if: contains(github.event.pull_request.labels.*.name, 'run-nala')
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run Nala
        uses: ./
        env:
          labels: ${{ join(github.event.pull_request.labels.*.name, ' ') }}
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
      - name: Persist JSON Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nala-results
          path: nala-results.json
          retention-days: 30
