name: Run Nala Visual Comparisons

on:
  workflow_dispatch:

jobs:
  action:
    name: Running visual comparison base image(s) update
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out nala screenshots repository
        uses: actions/checkout@v3
        with:
          repository: adobecom/nala-screenshots
          path: main
      - name: Copy over base screenshots to expected test screenshot path
        uses: ./runVisualPrep.sh
      - name: Run Nala
        uses: ./
        env:
          labels: ${{ join(github.event.pull_request.labels.*.name, ' ') }}
          isVisual: true
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
      - name: Copy, commit, and create PR of updated base images to screenshots repository
        uses: ./runVisualUpdate.sh
