name: Run Nala Visual Comparisons

on:
  workflow_dispatch:

jobs:
  action:
    name: Running visual comparison base image(s) update
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run Nala
        uses: ./
        env:
          labels: ${{ join(github.event.pull_request.labels.*.name, ' ') }}
          isVisual: true
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
      - name: Persist JSON Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nala-results
          path: nala-results.json
          retention-days: 30
      - name: Persist Screenshots Artifact
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: vc-screenshots-failures
          path: test-results/
          retention: 30
