name: Run Nala Visual Comparisons

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  action:
    name: Running visual comparison tests
    if: ${{ contains(join(github.event.pull_request.labels.*.name, ' '), 'run-') }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out nala screenshots repository
        uses: actions/checkout@v3
        with:
          repository: adobecom/nala-screenshots
          path: main
      - name: Copy over base screenshots to expected test screenshot path
        uses: ./runVisualPrep.sh
      - name: Run Nala
        uses: ./
        env:
          labels: ${{ join(github.event.pull_request.labels.*.name, ' ') }}
          isVisual: true
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
      - name: Persist JSON Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nala-results
          path: nala-results.json
          retention-days: 30
      - name: Persist Screenshots Artifact
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: vc-screenshots-failures
          path: test-results/
          retention: 30
